### ISSUE TITLE
Duplicate USB devices displayed

### ISSUE THREAD

**Issue by edent** [kgshank/gse-sound-output-device-chooser#104]
**Describe the bug**
My USB headset has a microphone and speaker. It shows up twice in the output list. Once as a USB Multichannel Output, and once as a pair of Headphones:

![Screenshot from 2020-06-05 15-13-34](https://user-images.githubusercontent.com/837136/83886736-66575880-a73f-11ea-9002-f562b33c4830.png)

The input list also has it twice. Once as S/PDIF and once as a regular microphone.
I also have a separate USB mic - that also shows up twice in the input list.
![Screenshot from 2020-06-05 15-14-07](https://user-images.githubusercontent.com/837136/83886734-65bec200-a73f-11ea-99f3-4eaf1385768d.png)

**Extension Information**
* Shell Version: 3.36.2
* Extension Version: Latest
* Install method (extension.gnome.org, AUR etc.): extension.gnome.org
* OS: Pop OS 20.04

**Error / Journal messages**
* Journal messages related to the error / extension.

**Comment by kgshank** [comment]
It seems like its considered as two different devices in the gnome sound setting. Please check and confirm. The extension just mimics the options in sound settings.
