### ISSUE TITLE
Names in "Port Settings" not meaningful enough

### ISSUE THREAD

**Issue by NicolasGoeddel** [kgshank/gse-sound-output-device-chooser#105]
**Describe the bug**
In the settings dialog I can choose weather I want to show or hide a port. The issue is that I've got there 4 times "Mikrofon", 2 times "Digitaleingang (S/PDIF)", 2 times "Digitalausgang (S/PDIF)", 2 times "Analoge Ausgabe" and so on.
![grafik](https://user-images.githubusercontent.com/1520064/87222732-a6c97800-c376-11ea-9481-9fffe8e0d2a8.png)
As you can see in the image I can not be sure which port I am hiding or showing. It would be nice to see the same names as in the actual chooser menu which looks like this:
![grafik](https://user-images.githubusercontent.com/1520064/87222778-150e3a80-c377-11ea-8317-fa1d23b7828d.png)

**Extension Information**
* Gnome Shell 3.36.2
* I don't know how to see that, but I installed it straight from here: https://extensions.gnome.org/extension/906/sound-output-device-chooser/
* Ubuntu 20.04

**Comment by sherbang** [comment]
In addition to the names not being specific enough, if I disable one "Microphone" in Port Settings then none of my Microphone devices show in the chooser anymore.

Here's two screenshots to demonstrate.  I hide one Microphone and both disappear.  This works the same if I set the second Microphone in the list to "Show" or "Default".
![2020-07-20_13-17 before](https://user-images.githubusercontent.com/275015/87966988-1bde3100-ca8c-11ea-8178-55228ff19965.png)
![2020-07-20_13-19 after](https://user-images.githubusercontent.com/275015/87966992-1e408b00-ca8c-11ea-8379-67d38e84b65d.png)

**Comment by kgshank** [comment]
It seems to due to the name conflicts. I will see how it can be fixed

**Comment by NicolasGoeddel** [comment]
Can I give that a slight push? ;-)

**Comment by kgshank** [comment]
@NicolasGoeddel  Fixes released for this issue. Available in git. Wait for update in extensions.gnome.org

**Comment by NicolasGoeddel** [comment]
Hey, thanks. It works now. Just updated the extension from extensions.gnome.org and it looks great now:
![grafik](https://user-images.githubusercontent.com/1520064/106384299-64c35a80-63ca-11eb-8c3d-198614ecea0b.png)
