### ISSUE TITLE
Keeps setting my mic volume to max from time to time

### ISSUE THREAD

**Issue by johnnyasantoss** [kgshank/gse-sound-output-device-chooser#106]
### Describe the bug
From time to time the extensions sets my mic volume to max. Tried disabling it and it stopped happening.

### Extension Information
* Shell Version 3.28.4
* Extension Version: no idea how to get that, since there's no about page and extensions.gnome.org doesn't show it
* Install method (extension.gnome.org, AUR etc.) extension.gnome.org
* OS Ubuntu 18.04.4

**Error / Journal messages**
* Journal messages related to the error / extension.

That was the only log I've found, since last boot, with `sound-output` in it.

```
17:58:53 gnome-software: failed to create an app for user/*/extensions-web/shell-extension/sound-output-device-chooser_kgshank.net/*
17:58:50 gnome-shell-ext: JS WARNING: [/home/johnny/.local/share/gnome-shell/extensions/sound-output-device-chooser@kgshank.net/convenience.js 200]: reference to undefined property Symbol.toPrimitive
```
Please, let me know if there's anything I can do to fix this. This is super annoying.

**Comment by kgshank** [comment]
The extension does not change the volume settings. Let me investigate further

**Comment by ajxn** [comment]
Is Ubuntu 18.04.4 still supported?  If not, you might want to close, and reopen if still valid.

**Comment by johnnyasantoss** [comment]
It doesn't happen anymore. I think it can be closed.
