### ISSUE TITLE
Devices with the same basic name cannot be shown/hidden separately

### ISSUE THREAD

**Issue by jifalops** [kgshank/gse-sound-output-device-chooser#109]
I have two `Digital Output (S/PDIF)` devices in the system's quick chooser:

![image](https://user-images.githubusercontent.com/826613/89938197-2bace900-dbe4-11ea-96a9-5bdaa137a2ff.png)

The problem is, in the options menu if I choose to hide either `Digital Output (S/PDIF)` entry, both are hidden:

![image](https://user-images.githubusercontent.com/826613/89937994-d53faa80-dbe3-11ea-87f5-f6912e83542c.png)

I'd like to only use the analog output of my headset, and hide it's digital output. If I hide it, then the digital output from my soundbar is no longer available.

**Extension Information**
* Shell Version: `GNOME Shell 3.36.1` | `GNU bash, version 5.0.16(1)-release (x86_64-pc-linux-gnu)`
* Extension Version: `?`
* Install method (extension.gnome.org, AUR etc.) `https://extensions.gnome.org/extension/906/sound-output-device-chooser/`
* OS: `Ubuntu 20.04`

**Comment by btouellette** [comment]
Seeing the same behavior on 3.38.1. Logs from setting first S/PDIF to Show and the second to Hide below. Leaves the settings panel in a weird state afterwards.

> Nov 27 13:09:12 pop-os gnome-shell[2430]: SDC Debug: Device Name:Digital Output (S/PDIF) (Built-in Audio)
> Nov 27 13:09:12 pop-os gnome-shell[2430]: SDC Debug: Profile:output:iec958-stereo
> Nov 27 13:09:12 pop-os gnome-shell[2430]: SDC Debug: Device Name:Line Out (Built-in Audio)
> Nov 27 13:09:12 pop-os gnome-shell[2430]: SDC Debug: Profile:output:analog-stereo
> Nov 27 13:09:12 pop-os gnome-shell[2430]: SDC Debug: Profile:output:analog-surround-21
> Nov 27 13:09:12 pop-os gnome-shell[2430]: SDC Debug: Profile:output:analog-surround-40
> Nov 27 13:09:12 pop-os gnome-shell[2430]: SDC Debug: Profile:output:analog-surround-41
> Nov 27 13:09:12 pop-os gnome-shell[2430]: SDC Debug: Profile:output:analog-surround-50
> Nov 27 13:09:12 pop-os gnome-shell[2430]: SDC Debug: Profile:output:analog-surround-51
> Nov 27 13:09:12 pop-os gnome-shell[2430]: SDC Debug: Profile:output:analog-surround-71
> Nov 27 13:09:12 pop-os gnome-shell[2430]: SDC Debug: Device Name:Digital Output (S/PDIF) (Corsair VOID PRO Wireless Gaming Headset)
> Nov 27 13:09:12 pop-os gnome-shell[2430]: SDC Debug: Profile:output:iec958-stereo
> Nov 27 13:09:14 pop-os gnome-shell[2430]: SDC Debug: Removed: 8
> Nov 27 13:09:14 pop-os gnome-shell[2430]: SDC Debug: Device Name:Line Out (Built-in Audio)
> Nov 27 13:09:14 pop-os gnome-shell[2430]: SDC Debug: Profile:output:analog-stereo
> Nov 27 13:09:14 pop-os gnome-shell[2430]: SDC Debug: Profile:output:analog-surround-21
> Nov 27 13:09:14 pop-os gnome-shell[2430]: SDC Debug: Profile:output:analog-surround-40
> Nov 27 13:09:14 pop-os gnome-shell[2430]: SDC Debug: Profile:output:analog-surround-41
> Nov 27 13:09:14 pop-os gnome-shell[2430]: SDC Debug: Profile:output:analog-surround-50
> Nov 27 13:09:14 pop-os gnome-shell[2430]: SDC Debug: Profile:output:analog-surround-51
> Nov 27 13:09:14 pop-os gnome-shell[2430]: SDC Debug: Profile:output:analog-surround-71
> Nov 27 13:09:14 pop-os gnome-shell[2430]: SDC Debug: Removed: 14
> Nov 27 13:09:15 pop-os gnome-shell[2430]: SDC Debug: Device Name:Digital Output (S/PDIF) (Built-in Audio)
> Nov 27 13:09:15 pop-os gnome-shell[2430]: SDC Debug: Profile:output:iec958-stereo
> Nov 27 13:09:15 pop-os gnome-shell[2430]: SDC Debug: Added: 8:Digital Output (S/PDIF):iec958-stereo-output
> Nov 27 13:09:15 pop-os gnome-shell[2430]: SDC Debug: Device Name:Line Out (Built-in Audio)
> Nov 27 13:09:15 pop-os gnome-shell[2430]: SDC Debug: Profile:output:analog-stereo
> Nov 27 13:09:15 pop-os gnome-shell[2430]: SDC Debug: Profile:output:analog-surround-21
> Nov 27 13:09:15 pop-os gnome-shell[2430]: SDC Debug: Profile:output:analog-surround-40
> Nov 27 13:09:15 pop-os gnome-shell[2430]: SDC Debug: Profile:output:analog-surround-41
> Nov 27 13:09:15 pop-os gnome-shell[2430]: SDC Debug: Profile:output:analog-surround-50
> Nov 27 13:09:15 pop-os gnome-shell[2430]: SDC Debug: Profile:output:analog-surround-51
> Nov 27 13:09:15 pop-os gnome-shell[2430]: SDC Debug: Profile:output:analog-surround-71
> Nov 27 13:09:15 pop-os gnome-shell[2430]: SDC Debug: Device Name:Digital Output (S/PDIF) (Corsair VOID PRO Wireless Gaming Headset)
> Nov 27 13:09:15 pop-os gnome-shell[2430]: SDC Debug: Profile:output:iec958-stereo
> Nov 27 13:09:15 pop-os gnome-shell[2430]: SDC Debug: Added: 14:Digital Output (S/PDIF):iec958-stereo-output
> Nov 27 13:09:21 pop-os gnome-shell[2430]: Can't update stage views actor StWidget is on because it needs an allocation.
> Nov 27 13:09:21 pop-os gnome-shell[2430]: message repeated 11 times: [ Can't update stage views actor StWidget is on because it needs an allocation.]

![image](https://user-images.githubusercontent.com/6272829/100484758-7c245580-30b2-11eb-8ea8-147e5daa4c90.png)

**Comment by kgshank** [comment]
Fixes released atlast.
