### ISSUE TITLE
Gnome-shell crashes when unplugging a device with audio capabilities.

### ISSUE THREAD

**Issue by Connor9220** [kgshank/gse-sound-output-device-chooser#110]
When unplugging a usb camera that has a built in microphone, gnome-shell crashes.  If I disable the plugin, gnome-shell doesn't crash.

**Comment by tomodachi** [comment]
@Connor9220  Could check if your pulseaudio daemon crashing when you disconnect your microphone?

meaning:
- disable the plugin, 
- check the start time of pulseaudio
- unplugg USB camera with microphone
- check if the start time of pulseaudio is different.

**Comment by Connor9220** [comment]
pulseaudio isn't affected. It stays running.
I disable the plugin, I can plug/unplug the USB camera with microphone without gnome-shell crashing.
I enable it, unplug it then crashes.

**Comment by tomodachi** [comment]
systemd will spawn a new pulseaudio if the current one crashes, did you verify by looking at the start time that it's the same time?

**Comment by Connor9220** [comment]
I have confirmed.  pulseaudio has the same start time and pid as before the crash.  It's stable.

**Comment by have-a-boy** [comment]
I assume this is caused by the same bug reported here: https://gitlab.gnome.org/GNOME/libgnome-volume-control/-/issues/9

I have exactly the same issue when disconnecting/turning off my USB DAC. Gnome-shell crashes immediately.
