### ISSUE TITLE
No sound output after switching to internal speaker when wired headphone is connected

### ISSUE THREAD

**Issue by raushankumar27** [kgshank/gse-sound-output-device-chooser#114]
When wired headphone is connected, switching to internal speaker does not give any sound output.
After disconnecting wired headphone, sound comes properly.

**Extension Information**
* Shell Version: 3.38
* Extension Version : 31
* Install method : extension.gnome.org,
* OS : Ubuntu 20.10 development branch

**Comment by kgshank** [comment]
It seems to be default behavior of gnome. Try disabling the extension and check how it works in gnome shell.

**Comment by raushankumar27** [comment]
yes, in gnome shell also, in sound setting page, it does not show internal speaker when wired headphone is connected

**Comment by kgshank** [comment]
Then, its not possible with the extension. It uses gnome sound settings as backbone. You should try with pulseaudio tools :)
