### ISSUE TITLE
Please add option to only show output devices

### ISSUE THREAD

**Issue by madig** [kgshank/gse-sound-output-device-chooser#12]
The extension shows input devices by default which I don't want to see because I don't care about them, but there is no option to hide those to make the extension behave like a few versions prior. Please add such an option.

**Comment by kgshank** [comment]
Will add an option in the next update

**Comment by kidwm** [comment]
@kgshank Thank you!

**Comment by auipga** [comment]
Shouldn't it also work by using "Hide for Single Device" when filtering the port settings so only one or none device is left? :(

**Comment by kgshank** [comment]
"Hide for Single Device" just hides the sub-menu. The active device is still shown. Working on the changes will be pushing soon.

**Comment by kgshank** [comment]
New updates pushed to git. extension waiting for approval in extensions.gnome.org
