### ISSUE TITLE
The today's update ends up in error, can't be resintalled afterwards

### ISSUE THREAD

**Issue by Shaltz** [kgshank/gse-sound-output-device-chooser#120]
Please provide the shell and extension information. It will be easier for me to understand the issue without too many unnecessary questions

**Describe the bug**
My system (ubuntu 20.04.1, fresh install 2 days old) prompted me for an update today.
I went for it but it ended up in error. I tried to uninstall and reinstall the extension
but it keeps on showing up as error now...

**Extension Information**
* Shell Version : 3.36.3
* Extension Version : latest
* Install method (extension.gnome.org, AUR etc.) : from extension.gnome.org
* OS : Ubuntu 20.04.1

**Error / Journal messages**
* Journal messages related to the error / extension.

**Comment by beruic** [comment]
I get this:
![Skærmbillede fra 2020-10-27 15-12-55](https://user-images.githubusercontent.com/724716/97313554-0fc1f680-1867-11eb-80d3-779a5ac5ec4c.png)

Does it work for you to log out and in again?

**Comment by beruic** [comment]
I fixed it by restarting Gnome. Press `Alt`+`F2` and enter `r` in the dialogue that appears.

**Comment by Shaltz** [comment]
Not an option for me right now, I am in a middle of my work day... I'll try this later on
thanks for the quick reply, I wasn't the only one facing this issue apparently ;)

**Comment by 127001** [comment]
Perhaps adding the 'restart requirement' to the description at the top of the extension page? The restart solved it for me too.

**Comment by rominail** [comment]
Same problem, restart worked for me

**Comment by kgshank** [comment]
This is part of gnome shell extension update  mechanism. It happens for all enabled extensions. Not specific to this one
