### ISSUE TITLE
Feature request: Hide menu items completely when there's only one option

### ISSUE THREAD

**Issue by 3ThumbsUp** [kgshank/gse-sound-output-device-chooser#121]
Hi

Great extension.

Regarding layout, there's an option to hide the selector when there's only one device, but even with that option enabled it still leaves a menu item that doesn't do anything at all. I think it would look cleaner if the extension completely removed the entire row when it doesn't do anything.

Thanks

**Comment by kgshank** [comment]
:+1:

**Comment by kgshank** [comment]
Fixes available in current Git version, please test if possible

**Comment by kgshank** [comment]
Fixed in the latest release. Closing ticket
