### ISSUE TITLE
Transparent icon in extension

### ISSUE THREAD

**Issue by Areku-The-OF** [kgshank/gse-sound-output-device-chooser#122]
I recently updated Pop!_OS to 20.10 and when updating the extensions I noticed that the extension icon shows kind of transparent compared to the rest. Other than that, the extension is working as intended.

![Screenshot from 2020-12-01 12-28-32](https://user-images.githubusercontent.com/73086862/100769205-1a296000-33d2-11eb-8406-76226389ee5a.png)
![Screenshot from 2020-12-01 12-52-00](https://user-images.githubusercontent.com/73086862/100770808-0f6fca80-33d4-11eb-90b1-3d4c502efe3e.png)

GNOME Shell 3.38.1
Version 32, installed from extensions.gnome.org
Pop!_OS 20.10

**Comment by kgshank** [comment]
The icon is from the theme POP os is using.  There is no icon as part of this extension :(
