### ISSUE TITLE
Feature Request - Filter out devices

### ISSUE THREAD

**Issue by leoheck** [kgshank/gse-sound-output-device-chooser#123]
So, I have a lot of devices. Is it possible to customize this extension to filter out some things from here?
I would like to keep the Headphones and the built-in speaker.
It is always a pain to find the right thing before a meeting.
![image](https://user-images.githubusercontent.com/1277920/101295704-16e10a80-37fe-11eb-9259-7b30d254b7e5.png)

Also, I have one of the built-in speakers with problems on my Dell XPS (I saw this happening a lot)
But I can fix issues by changing the balance towards the good speaker. 
So I would like to ask if it is possible to add the balance bar, so I can balance my speakers right from the menu.

The OS is Ubuntu 20.04
I am using the latest version I could install, I don't know how to get the versions requires, sorry.

Ah, and those devices appear when I plug my monitor that is a dock station, also from Dell.

**Comment by kgshank** [comment]
There is a filter option in the settings already, please try that.

![Screenshot from 2020-12-09 18-57-12](https://user-images.githubusercontent.com/10281027/101668145-77678600-3a50-11eb-9a7f-6caf985bf97c.png)

**Comment by leoheck** [comment]
Oh, nice. Where I can find these settings?

**Comment by leoheck** [comment]
Cool, I was able to find it with Gnome-Tweak tool.
Do you know a different way to launch this settings page?

By the way, this is my current setting. It has a lot of devices.
![image](https://user-images.githubusercontent.com/1277920/101774562-0ade9c80-3acd-11eb-9c1c-6358b4b320a0.png)

**Comment by leoheck** [comment]
Is it possible to see/have more info about the devices under the Port Settings list?
For instance, I am seeing:
- 3x Microphones
- 2x Speakers

**Comment by kgshank** [comment]
Yes, its confusing. I have to rework on how the device name is displayed.

**Comment by leoheck** [comment]
@kgshank I saw it is not working perfectly yet.
For instance, I have disabled a second Speaker... then both disappeared... it looks like the filter has to be improved too.
Also, maybe this happens just because the names are equal there. You can work with me then I can give more info as you may need to understand how to filter these things properly.

**Comment by leoheck** [comment]
@kgshank check this. 
The speaker and the microphone came from the same source (my wired earphone)
They start with different names. Every day I spend some time trying to select both from the same source (Headphone adapter)

Why not move the "Headphone Adapter" to the start of the string. It will be much easier to find these things, especially when you have tons of devices as I do.

![image](https://user-images.githubusercontent.com/1277920/102521456-b8285600-4073-11eb-823e-56bd7bdbad03.png)

**Comment by kgshank** [comment]
@leoheck  I will implement this as an option. Not getting enough time to spend, hopefully over the holidays :(

**Comment by leoheck** [comment]
@kgshank having a better understanding of these devices will be helpful. Thanks for at least giving me hope. I hope you can have enough time. Thank you.

**Comment by terencode** [comment]
Would be nice to also have an option like in pavucontrol to filter out virtual input/output devices and also monitors.

**Comment by kgshank** [comment]
@leoheck  Fixes released v33 (extension approval pending)

@terencode  I will look into this

**Comment by leoheck** [comment]
Hey @kgshank I am seeing these undefined things here in settings.
Maybe something didn't go well.
![image](https://user-images.githubusercontent.com/1277920/105562575-77b69a80-5cf9-11eb-980b-516d882678ea.png)

**Comment by kgshank** [comment]
@leoheck Fixes released. Available in git already. It will take time for approval in extensions.gnome.org

**Comment by sakrow** [comment]
I would like to choose some devices, but nothing appears.

I'm in Ubuntu 18.04.5 LTS (Dell XPS 9560)

![imagen](https://user-images.githubusercontent.com/5989947/106740307-8286fe80-661a-11eb-92d8-1bb2135c4eb5.png)

**Comment by leoheck** [comment]
Strange, I have this. on Ubuntu 20.04 (Dell XPS 9350)
![image](https://user-images.githubusercontent.com/1277920/106764709-ce37a900-6616-11eb-9592-bf2893def79f.png)


@kgshank these names are still long. 
And it doesn't look good marking it to show long names. 
And also we still have different names for the Speaker and Microphone.
For instance,  it is better to use the Microphone on the Speaker device if it has. So both are coming from the same device.
And you can see here, these pairs still have different names.
So the question is it possible to have the same name for the mic and speaker so it is easy to select both from the same source?
A way to rename or give labels to these devices would be nice to have. So the user can improve what he is going to see there on the menu.
![image](https://user-images.githubusercontent.com/1277920/106764897-02ab6500-6617-11eb-9ea3-21b1695e6e1d.png)

**Comment by sakrow** [comment]
¿Some other way to list this devices? Any log to view?

**Comment by leoheck** [comment]
Not sure how this plugin works and if it has logs. I would like to know too.

But, there is this command that you can check on the command line to have something to compare. 
```arecord -l```

![image](https://user-images.githubusercontent.com/1277920/106769802-202efd80-661c-11eb-9f46-2c578d87993b.png)

**Comment by sakrow** [comment]
Here i can view my devices:

![imagen](https://user-images.githubusercontent.com/5989947/106771868-bd4f5d80-663f-11eb-91e1-8ba6c54d6539.png)

**Comment by kgshank** [comment]
> I would like to choose some devices, but nothing appears.
> 
> I'm in Ubuntu 18.04.5 LTS (Dell XPS 9560)
> 
> ![imagen](https://user-images.githubusercontent.com/5989947/106740307-8286fe80-661a-11eb-92d8-1bb2135c4eb5.png)

Unfortunately, the extension version installed has language dependency. It works only with English as display language. The later versions of the extension can work with all languages, but its not compatible with gnome 3.28

**Comment by sakrow** [comment]
Great I changed my laptop language to English and now works fine.

Thanks.

**Comment by kgshank** [comment]
@sakrow 

Give this a try, change this line from
`let [result, out, err, exit_code] = GLib.spawn_command_line_sync('pactl list cards');`
to
`let [result, out, err, exit_code] = GLib.spawn_command_line_sync('LANG=C pactl list cards');`

in the file convenience.js in the extension directory.

If it works, then you can use your display language

**Comment by kgshank** [comment]
@sakrow 

Give this a try, change this line from
`let [result, out, err, exit_code] = GLib.spawn_command_line_sync('pactl list cards');`
to
`let env = GLib.get_environ ();`
`env = GLib.environ_setenv (env, "LANG", "C", true);`
`let [result, out, err, exit_code] = GLib.spawn_sync(null,['pactl', 'list','cards'], env, GLib.SpawnFlags.Default,null);`

in the file convenience.js in the extension directory.

If it works, then you can use your display language

**Comment by kgshank** [comment]
> Strange, I have this. on Ubuntu 20.04 (Dell XPS 9350)
> ![image](https://user-images.githubusercontent.com/1277920/106764709-ce37a900-6616-11eb-9592-bf2893def79f.png)
> 
> @kgshank these names are still long.
> And it doesn't look good marking it to show long names.
> And also we still have different names for the Speaker and Microphone.
> For instance, it is better to use the Microphone on the Speaker device if it has. So both are coming from the same device.
> And you can see here, these pairs still have different names.
> So the question is it possible to have the same name for the mic and speaker so it is easy to select both from the same source?
> A way to rename or give labels to these devices would be nice to have. So the user can improve what he is going to see there on the menu.
> ![image](https://user-images.githubusercontent.com/1277920/106764897-02ab6500-6617-11eb-9ea3-21b1695e6e1d.png)

@leoheck It seems like the names are messed up. If they are from the same source, the names should be the same. Can you post a screenshot of the Gnome Control Center -> Sound Settings with the drop downs expanded?

**Comment by kgshank** [comment]
@leoheck  Is this issue resolved? Please confirm

**Comment by leoheck** [comment]
Here some screenshots. I think it is fixed this time. 

![image](https://user-images.githubusercontent.com/1277920/112377705-d7fb9580-8cc4-11eb-8b09-e08a99cb20cb.png)
![image](https://user-images.githubusercontent.com/1277920/112377876-01b4bc80-8cc5-11eb-9373-6682eaa2fa2c.png)
