### ISSUE TITLE
switch output device in settings not working when extension is installed

### ISSUE THREAD

**Issue by thorstenhirsch** [kgshank/gse-sound-output-device-chooser#124]
**Describe the bug**
After installing the extension there are 2 places in Gnome to change the output device:

- in the status menu (that's what this extension is for)
- in the Gnome settings under sound

Switching the output device in the Gnome settings has no effect anymore.

**Extension Information**
* Shell Version: 3.38.2
* Extension Version: latest (I guess, because there's no update icon on extension.gnome.org)
* Install method: extension.gnome.org
* OS: Arch Linux

**Error / Journal messages**
* Journal messages related to the error / extension: no journal message appears when switching the output device in the Gnome settings

**Comment by kgshank** [comment]
I am using Manjaro and  I can select devices in both settings and extension as well. Try posting the last lines from journalctl after selecting the device in settings, even though if its not related to the extension

**Comment by thorstenhirsch** [comment]
Okay. Let me give you the 2 last lines:
```
Dez 09 19:01:01 myhostname CROND[40050]: (root) CMD (run-parts /etc/cron.hourly)
Dez 09 19:01:32 myhostname systemd[1244]: Started Application launched by gnome-shell.
```
In the Gnome settings I switched from loudspeakers (SPDIF) to headphones (analogue), but it had no effect.

**Comment by kgshank** [comment]
1. Can you select after you disable extension?
2. Have you enabled Log messages for the extension the the extension preferences under Miscellanous?

**Comment by thorstenhirsch** [comment]
1. No. Doesn't work anymore, not after disabling it, and not even after a reboot (while disabled). But I'm 100% sure that it was working before I installed the extension.

2. Okay, I just enabled them and now every time I switch the output one of these messages appears:

```
Dez 09 19:49:29 myhostname gnome-shell[2196]: SDC Debug: Activated: 1
Dez 09 19:49:42 myhostname gnome-shell[2196]: SDC Debug: Activated: 3
```

**Comment by kgshank** [comment]
I can only see that the extension is responding to two device activations. First a device (id 1) is activated and immediately another device (id 3) is activated. The extension does not activate any device automatically, except only when the active device is removed like removing an active HDMI cable or bluetooth headset. From what you have explained, there is no device removal here. To confirm post the full output of

`journalctl -r | grep SDC Debug`

**Comment by thorstenhirsch** [comment]
Fully agree, there's no device removal. And the debug messages in my last post don't belong to a single event, but to two events. So SDC is working just fine. One switch event, one debug message, one successful device switch.

I just wonder how the "control" of device switching moved from Gnome Settings to SDC and how to undo it.

**Comment by kgshank** [comment]
Try after renaming the folder ~/.config/pulse  and restart pulseaudio/system
