### ISSUE TITLE
Multiple Dummy Outputs in output list

### ISSUE THREAD

**Issue by jvanheugten** [kgshank/gse-sound-output-device-chooser#125]
**Describe the bug**
When I try to select my device from the menu it shows, besides my normal audio outputs, multiple "Dummy Outputs". These Dummy Outputs do not show in the list of `aplay -l` nor in the Ubuntu sound settings. The number of Dummy Outputs also seems to change from 0 to 3.

**Extension Information**
* Shell Version: Gnome 3.36.3
* Extension Version: ?
* Install method: extension.gnome.org
* OS: Ubuntu 20.04

**Comment by kgshank** [comment]
Please post the output of `pactl -list`

**Comment by jvanheugten** [comment]
Strangely the problem has gone away. I think some update might have been applied that fixed it for me.
Thanks anyway.

**Comment by hubick** [comment]
I'm seeing this too on Fedora 33 current, any idea what might have fixed it? 
![sound_chooser_dummy_outputs](https://user-images.githubusercontent.com/599638/103144297-62435600-46e4-11eb-9769-1cd566d780bf.png)
[pactl_list.txt](https://github.com/kgshank/gse-sound-output-device-chooser/files/5742592/pactl_list.txt)

**Comment by hubick** [comment]
And somehow after a reboot today for a few system updates, all the Dummy Outputs are gone now for me as well. Huh. Nevermind I guess.
