### ISSUE TITLE
Regression: TypeError: this._devices[id] is undefined after unloading module-jack-sink 

### ISSUE THREAD

**Issue by terencode** [kgshank/gse-sound-output-device-chooser#128]
After starting/stopping jack using cadence which also loads/unloads module-jack-sink/source I get the following in the log: 
```
JS ERROR: TypeError: this._devices[id] is undefined
                                                     _setChooserVisibility@/usr/share/gnome-shell/extensions/sound-output-device-chooser@kgshank.net/base.js:367:13
                                                     _deviceRemoved@/usr/share/gnome-shell/extensions/sound-output-device-chooser@kgshank.net/base.js:290:18
```
This seems to have been introduced by #126.

Not sure if part of the same bug but I also appear to have duplicated entries for my usb sound card. 

**Extension Information**
* Shell Version 3.38.2
* Extension up until a702711
* Install method AUR 
* OS Archlinux

**Comment by kgshank** [comment]
The commit is reverted and fixes for the original issue released. AUR should pull directly from the git, i hope

**Comment by terencode** [comment]
>  AUR should pull directly from the git, i hope

Yes it does :)

> The commit is reverted and fixes for the original issue released.

Confirmed the error message is no longer present and gnome-shell still doesn't crash.

Your new port settings changes are great but brought some bugs:

When I select the input/output I get a bunch of messages, here are some of them:

- gsd-media-keys : `gvc_mixer_ui_device_get_description: assertion 'GVC_IS_MIXER_UI_DEVICE (device)' failed`
 `Sync_devices: Failed to match stream id: 45, description: 'Digital Output (S/PDIF)', origin: 'Starship/Matisse HD Audio Controller Digital Stereo (IEC958)'`

- gjs / gnome-shell : `gvc_mixer_card_get_index: assertion 'GVC_IS_MIXER_CARD (card)' failed`

Also by playing with hide/show and selecting an input/output I made libpulse crash which in turns crashed gnome-shell.
I unfortunately haven't checked yet for a reproducer.

Ah and finally the S/PDIF  digital output don't appear in the port list so I can't hide them but I think I could before?

**Comment by terencode** [comment]
Oh and last but not least  now I can't select the jack-sink / source in the dropdowns and they don't appear in the port list.

**Comment by kgshank** [comment]
Can you post the extension messages as well from journal when you get these messages

    gsd-media-keys : gvc_mixer_ui_device_get_description: assertion 'GVC_IS_MIXER_UI_DEVICE (device)' failed
    Sync_devices: Failed to match stream id: 45, description: 'Digital Output (S/PDIF)', origin: 'Starship/Matisse HD Audio Controller Digital Stereo (IEC958)'

    gjs / gnome-shell : gvc_mixer_card_get_index: assertion 'GVC_IS_MIXER_CARD (card)' failed.

There are no changes in the available devices in the port list, only the display name is changed and show always option is removed as it created other issues. 

In any case, if you can post some more messages from the extension, it will help me understand the issue

**Comment by terencode** [comment]
Here is the log:  [debug.txt](https://github.com/kgshank/gse-sound-output-device-chooser/files/5821819/debug.txt)

This is when I enable the extension, do some intput/output switches and then reconnect my usb soundcard (the scarlett solo) and try again.

Unfortunately I still don't have a solid reproducers for some messages or the crash.

Also here is a screenshots of the settings:
![image](https://user-images.githubusercontent.com/12665563/104754650-c3959c80-5759-11eb-8425-86a84850ce91.png)


What's weird is while I set the usb soundcard as analog duplex it keeps reappearing with the digital profile.

Should I open a separate issues about not being able to hide S/PDIF ?

**Comment by terencode** [comment]
With your last commit (f94b642) I can filter S/PDIF and jack-sink/source appear again, thanks!

I'm going to close the issue as the original problem was fixed and the most annoying regressions from new code as well, thank you!
