### ISSUE TITLE
[Feature Request] Auto hide when not in use (mic)

### ISSUE THREAD

**Issue by arthurflor23** [kgshank/gse-sound-output-device-chooser#129]
**Describe the bug**
Currently, gnome automatically hides the microphone when not in use, but I noticed that the extension keeps the icon active in the menu all the time:

Gnome without extension:
![image](https://user-images.githubusercontent.com/11759042/104459321-59c79800-558b-11eb-9d67-30999f884829.png)

Gnome with extension:
![image](https://user-images.githubusercontent.com/11759042/104459367-66e48700-558b-11eb-924e-115859ccfca1.png)

Would it be possible to follow the same behavior as gnome? I think that would solve the question of the icon being without color all the time in the bar, and when it is in use, it would appear filled with the volume of the input.

Anyway, thanks for the extension.

**Extension Information**
* Shell Version: Gnome 3.38.2
* Extension Version: 3.38.32
* Install method: extension.gnome.org
* OS: Arch Linux

**Comment by kgshank** [comment]
I will look into this

**Comment by kgshank** [comment]
Unfortunately, I couldn't implement this feature. The changes I make to control the indicator is breaking shell. I will see if there is a different way to handle this

**Comment by arthurflor23** [comment]
Yes, it was fixed.
