### ISSUE TITLE
GLib.FileError

### ISSUE THREAD

**Issue by johnnydvc** [kgshank/gse-sound-output-device-chooser#13]
GLib.FileError: Datei »/usr/share/gnome-shell/extensions/sound-output-device-chooser@kgshank.net/ui/prefs-dialog.gtkbuilder« konnte nicht geöffnet werden: No such file or directory

Stack trace:
  SDCSettingsWidget<._init@/usr/share/gnome-shell/extensions/sound-output-device-chooser@kgshank.net/prefs.js:56
  wrapper@resource:///org/gnome/gjs/modules/lang.js:178
  buildPrefsWidget@/usr/share/gnome-shell/extensions/sound-output-device-chooser@kgshank.net/prefs.js:196
  Application<._selectExtension@resource:///org/gnome/shell/extensionPrefs/main.js:90
  wrapper@resource:///org/gnome/gjs/modules/lang.js:178
  Application<._onCommandLine@resource:///org/gnome/shell/extensionPrefs/main.js:238
  wrapper@resource:///org/gnome/gjs/modules/lang.js:178
  main@resource:///org/gnome/shell/extensionPrefs/main.js:376
  @<main>:1

**Comment by kgshank** [comment]
Your installation is missing ui related files. Did you install from extensions.gnome.org. The installation path shows /usr/share

**Comment by micealgallagher** [comment]
I got this after installation from the AUR. Reinstallation from extensions.gnome.org does the trick
