### ISSUE TITLE
Extension prevents tray icon from appearing

### ISSUE THREAD

**Issue by danielsanfr** [kgshank/gse-sound-output-device-chooser#130]
## Description

Basically when I enable this extension the CopyQ tray icon does not appear.
It might help to take a look at the comments on the issue: https://github.com/hluk/CopyQ/issues/1526

## Extension Information
- Shell Version: 3.38.2
- Extension Version: 32
- Install method: extension.gnome.org
- OS: Manjaro Linux - rolling

**Comment by kgshank** [comment]
I tried installing copyq and the tray icon is not appearing even the extension is not enabled. The extension does not interact with the tray icons. I believe this is not related to the extension. If possible send me some journal messages when the icon is not appearing
