### ISSUE TITLE
Jack sink/source is not shown in the latest version of the extension

### ISSUE THREAD

**Issue by bugnano** [kgshank/gse-sound-output-device-chooser#135]
I use this extension since more than a year, without any issue.
After upgrading to the latest version, I found a regression:

When I log in GNOME, I have only PulseAudio running. When I manually start Jack via Cadence, the PulseAudio input and output get automatically switched to the Jack source and Jack sink.
The problem is that the latest version of this extension does not show the Jack sink and source, and shows the input and output devices that were selected before starting Jack. However, if I go to the sound settings in the GNOME settings manager, I see that the PulseAudio input and output are indeed Jack source and sink.

**Extension Information**
* Shell Version 3.36
* Extension Version Latest from extensions.gnome.org as of 2021-01-30
* Install method extensions.gnome.org
* OS Fedora 32

**Comment by kgshank** [comment]
The fixes are already available in the git. The new version is not approved in extensions.gnome.org. If possible, try installing from the git directly

**Comment by AlynxZhou** [comment]
Try restart your gnome-shell manually by alt+f2 then type r enter, and jack will show.

**Comment by bugnano** [comment]
> Try restart your gnome-shell manually by alt+f2 then type r enter, and jack will show.

I use this extension in order to not have the inconvenience of opening the sound settings. Having the bigger inconvenience of restarting the shell defeats the purpose of this extension.

That being said, the issue seems fixed in the latest version from extensions.gnome.org, so I think that we can close this issue as resolved.
