### ISSUE TITLE
New version does not install from extensions.gnome.org

### ISSUE THREAD

**Issue by RensOliemans** [kgshank/gse-sound-output-device-chooser#137]
**Description**
Installing the newest version from extensions.gnome.org does not work anymore, installing it results in 'ERROR'.
Other people seem to have the same problem as well, as seen in comments (https://extensions.gnome.org/extension/906/sound-output-device-chooser/)

**Extension Information**
* gnome-shell version: 3.38.2
* extension version: Not sure, newest available in extensions.gnome.org
* Install method: extension.gnome.org
* Ubuntu 20.10

**Error / Journal messages**
* Haven't installed locally, will it help if I do that?

**Comment by RensOliemans** [comment]
Not sure how to get improved logging from extensions.gnome.org, if there are ways please let me know

**Comment by kgshank** [comment]
Try restarting the shell, the updates in extensions.gnome.org ends in error for most extensions.

**Comment by SimonDeussen** [comment]
I have the same problems as RensOliemans.  
Restarting and reinstallation does not fix this issue for me.


**Extension Information**
-     gnome-shell version: 3.36.4
-     extension version: Not sure, newest available in extensions.gnome.org
-     Install method: extension.gnome.org
-     Ubuntu 20.04

**Comment by tkazik** [comment]
I can also confirm this, same setup as @SimonDeussen. Thx for your investigations!

**Comment by dsommers** [comment]
I just upgraded to 3.38.35 from 3.38.34  on RHEL-8.3 and it is no longer working.  Trying to access the settings via "GNOME Tweaks" gives me a "Something's gone wrong" window with the following technical details:

```
Gtk.BuilderError: /home/user/.local/share/gnome-shell/extensions/sound-output-device-chooser@kgshank.net/ui/prefs-dialog.glade:5:1 Required gtk+ version 3.24, current version is 3.22

Stack trace:
  _init@/home/user/.local/share/gnome-shell/extensions/sound-output-device-chooser@kgshank.net/prefs.js:123:13
  wrapper@resource:///org/gnome/gjs/modules/_legacy.js:82:22
  buildPrefsWidget@/home/user/.local/share/gnome-shell/extensions/sound-output-device-chooser@kgshank.net/prefs.js:279:27
  _selectExtension@resource:///org/gnome/shell/extensionPrefs/main.js:75:22
  _onCommandLine@resource:///org/gnome/shell/extensionPrefs/main.js:320:17
  main@resource:///org/gnome/shell/extensionPrefs/main.js:635:5
  @<main>:1:43
```

Could this be the issue others are seeing as well?

Manually downgrading to [3.38.34](https://github.com/kgshank/gse-sound-output-device-chooser/releases/tag/34) restores the functionality.  My downgrade process was simply to remove the `/home/user/.local/share/gnome-shell/extensions/sound-output-device-chooser@kgshank.net/`directory, unpack the same directory from the downloaded tarball and restart GNOME Shell (ALT-F2 r)

**Comment by dsommers** [comment]
Okay, tested this version.  Now I can access the settings, but no audio devices appears in the "menu", and there is an alert about some errors; both in https://extensions.gnome.org/local/ and GNOME Tweaks.  Checking `journalctl` gives me this line:

    Extension "sound-output-device-chooser@kgshank.net" had error: TypeError: GObject.registerClass() used with invalid base class (is PopupMenuItem)

**Comment by kgshank** [comment]
@dsommers  Whats the shell version. This seems to be a problem with older shell version

**Comment by dsommers** [comment]
@kgshank This is GNOME 3.32.2 on an up-to-date RHEL-8.3 installation.

**Comment by ramonribeiro96** [comment]
works on ubuntu 20.10 don't forget to restart gnome after updating to fix error message

do this with
1.Alt+F2
2.type in "r" or "restart"
3.wait till its done restarting
4.refresh page and its now working

**Comment by kgshank** [comment]
@dsommers Please test 3.32 branch from git, I have pushed some changes. Please let me know, I will merge the changes to master

**Comment by dsommers** [comment]
> @dsommers Please test 3.32 branch from git, I have pushed some changes. Please let me know, I will merge the changes to master

@kgshank This works like a charm; just did a git clone, checkout of 3.22 branch, ran `make install` and restarted GNOME Shell.   I see a lot of `SDC Debug:` messages in `journalctl`, which lists audio interfaces - but nothing else related to this extension or other multimedia related features.

**Comment by kgshank** [comment]
@dsommers  You can disable Log messages in preferences, the recent changes have lots of messages to help in debugging :)

**Comment by dsommers** [comment]
> @dsommers You can disable Log messages in preferences, the recent changes have lots of messages to help in debugging :)

Hah!  Indeed!  Thanks!  I might have enabled debugging to get a better overview with the prior errors.  I'll test this more carefully coming week, as I have some more USB audio cards which is in use at the office desks and such.

**Comment by boistordu** [comment]
But I would really like to know why the extension is always ending in error. Is it because of the bad management of gnome shell or is it something else ?

**Comment by atais** [comment]
I am on ubuntu 20.04 and the version from the store does not work for me well as well.

But I have reverted to v35 and everything works again:


```
cd ~/.local/share/gnome-shell/extensions/

# Remove older version
rm -rf "*sound-output-device-chooser*"

# Clone current version
git clone https://github.com/kgshank/gse-sound-output-device-chooser.git

# Checkout 35
git checkout tags/35 -b 35

# Install it
ln -s gse-sound-output-device-chooser/sound-output-device-chooser@kgshank.net/ sound-output-device-chooser@kgshank.net
```

**Comment by dsommers** [comment]
Just retested latest git master (685fee4a4255e006a6085aad3d70df774e253fa3) on a ThinkPad X1Cgen8 with a Thundebolt docking with audio connected, running RHEL 8.3 with GNOME 3.32.2 (up-to-date version on RHEL).  Using two additional USB audio cards on top of that.  All audio 7 input + 10 outputs detected and listed properly.

**Comment by kgshank** [comment]
sorry for the issues, i was probably sleeping when i pushed the last update :( The fixes are available in git now. I will release v38 with the changes

**Comment by boistordu** [comment]
@kgshank did you look back at the problem of the "extension initializing"? And also why at each update there is an error ? I had to restart the gnome-shell or restart the pc to make it work... is it linked to my setup or is it a general problem ?

**Comment by kgshank** [comment]
@boistordu The error "extension initializing" is due to a faulty update from my side. I fixed it, you can install from git now. 

After updating form extensions.gnome.org, the update shows error and after restart or logout/login from gnome, this error will be gone. This is an issue with gnome and cannot be fixed from my side

**Comment by boistordu** [comment]
Aaah thanks 🙏 I finally know why I have always this error message when updating your extension. 
@kgshank do you need us to put pressure somewhere ? Like on the gnome GitLab to make them resolve this issue ? If you have open a ticket of course about it...

**Comment by kgshank** [comment]
No i dont have any open tickets from my side, but since it affects many extensions, there should be a fix soon, i hope

**Comment by boistordu** [comment]
Well it has been around for like a year now certainly. Maybe more so I think it would be nice to put a ticket in place on their gitlab on this... so if you have some time to put it or one of us can do it if you prefer.

**Comment by MarvinMep** [comment]
I've been getting the error when trying to upgrade from https://extensions.gnome.org too until this morning. Now, removed the extension (via Gnome Extensions app), restarted Shell (Alt+F2, r) and then I went back to extensions.gnome.org and installed again. It started to work instantly. I restarted the whole system and it still works fine.
On Debian bullseye/GNOME 3.38.4

**Comment by Basster** [comment]
Just wanted to tell you, that V40.38 works great here at Ubuntu 20.04.2, GNOME Shell 3.36.4, updated via release tarball.

**Comment by boistordu** [comment]
We still don't have the updates on extensions.gnomes.org 
Is it supposed to take that much time? You said that you were uploading the new version to git past week end... and still be update on the main platform

**Comment by kgshank** [comment]
Its updated now, please check in extensions.gnome.org
