### ISSUE TITLE
Sound chooser doesn't start, no icon in menu

### ISSUE THREAD

**Issue by speedy-10** [kgshank/gse-sound-output-device-chooser#138]
Hi, if I activate the extension, i got the following error message in a terminal:

`gnome-shell[1608]: ../clutter/clutter/clutter-actor.c:10558: The clutter_actor_set_allocation() function can only be called from within the implementation of the ClutterActor::allocate() virtual function.`

`Kernel: 5.8.0-41-generic x86_64 bits: 64 
 Desktop: Gnome 3.36.4 Distro: Ubuntu 20.04.2 LTS (Focal Fossa) `

**Comment by terencode** [comment]
Regression introduced by 11546cf0d6aec452f02e4030787866e171f2f186 I think as the extension works when it's reverted.

**Comment by kgshank** [comment]
@terencode Did you update from git? I will check once again, the commit just introduces lang env variable for command execution.

**Comment by terencode** [comment]
Yeah it's updated from git and I'm 100% sure the last commit is the culprit:

```
févr. 07 14:26:00 terence-desktop gnome-shell[1987]: SDC Debug: SDC: init
févr. 07 14:26:00 terence-desktop gnome-shell[1987]: SDC Debug: Constructoroutput
févr. 07 14:26:00 terence-desktop gnome-shell[1987]: SDC Debug: Max Id:23
févr. 07 14:26:00 terence-desktop gnome-shell[1987]: SDC Debug: Added - 1
févr. 07 14:26:00 terence-desktop gnome-shell[1987]: SDC Debug: Old logic
févr. 07 14:26:00 terence-desktop gnome-shell[1987]: SDC Debug: ERROR: pactl execution failed. No ports/profiles will be displayedGLib.SpawnError: Failed to execute child process “pactl” (No such file or directory)
```

**Comment by kgshank** [comment]
@terencode Please check now, I have committed fixes

**Comment by terencode** [comment]
Your new commit works but note that you pushed the new commit to the `40` branch and not master so I had to apply it manually.

**Comment by speedy-10** [comment]
Thanks for your work. When will it be available to install from https://extensions.gnome.org/ again?

**Comment by kgshank** [comment]
@speedy-10 I am rewriting the extension completely to avoid shell crashes, I will update all changes together

**Comment by speedy-10** [comment]
That's great, thanks a lot.

**Comment by speedy-10** [comment]
Works perfect, no error messages, thanks.
