### ISSUE TITLE
PipeWire(-pulse) support

### ISSUE THREAD

**Issue by cbix** [kgshank/gse-sound-output-device-chooser#139]
**Describe the bug**
When using PipeWire 0.3.21 with the PulseAudio compatibility service as the main Desktop audio stack, the extension wouldn't load with the error pasted below. `pavucontrol` however works as expected.

I am aware that this could very well be a lack of API compatibility in `pipewire-pulse`, but would anyway love to see this extension working again and would even spend some time on contributing actual PipeWire support.

**Extension Information**
* Shell Version: GNOME Shell 3.38.3
* Extension Version: 34
* Install method: extension.gnome.org
* OS: Arch Linux with `pipewire` and `pipewire-pulse`, see this [ArchWiki article](https://wiki.archlinux.org/index.php/PipeWire#PulseAudio_clients)

**Error / Journal messages**
```
JS ERROR: Extension sound-output-device-chooser@kgshank.net: TypeError: uidevice.description is null
_deviceAdded@/home/florian/.local/share/gnome-shell/extensions/sound-output-device-chooser@kgshank.net/base.js:147:17
_onControlStateChanged@/home/florian/.local/share/gnome-shell/extensions/sound-output-device-chooser@kgshank.net/base.js:102:41
SoundDeviceChooserBase@/home/florian/.local/share/gnome-shell/extensions/sound-output-device-chooser@kgshank.net/base.js:52:18
SoundOutputDeviceChooser@/home/florian/.local/share/gnome-shell/extensions/sound-output-device-chooser@kgshank.net/extension.js:32:9
enable@/home/florian/.local/share/gnome-shell/extensions/sound-output-device-chooser@kgshank.net/extension.js:124:36
_callExtensionEnable@resource:///org/gnome/shell/ui/extensionSystem.js:167:32
_onEnabledExtensionsChanged/<@resource:///org/gnome/shell/ui/extensionSystem.js:491:35
_onEnabledExtensionsChanged@resource:///org/gnome/shell/ui/extensionSystem.js:491:14
createCheckedMethod/<@resource:///org/gnome/gjs/modules/core/overrides/Gio.js:533:46
enableExtension@resource:///org/gnome/shell/ui/extensionSystem.js:194:29
EnableExtension@resource:///org/gnome/shell/ui/shellDBus.js:307:38
_handleMethodCall@resource:///org/gnome/gjs/modules/core/overrides/Gio.js:327:38
_wrapJSObject/<@resource:///org/gnome/gjs/modules/core/overrides/Gio.js:404:34
```

**Comment by Razzeee** [comment]
It does show fine for me on initial start, it seems to get lost after hilbernate.

It also seems to not switch the device correctly, at least not instantly, but gnome control panel seems to have the same problem.

**Comment by kgshank** [comment]
The git version has fixes for this. I havent personally tested with pipewire, but the error in the journal should not occur atleast. Please check with the git version

**Comment by cbix** [comment]
Thanks for the hint, everything seems to work flawlessly with latest master and PW 0.3.24 🎉 Thanks for all the work!
