### ISSUE TITLE
Request: Please add option to continue last "intentional" device choice 

### ISSUE THREAD

**Issue by ilippert** [kgshank/gse-sound-output-device-chooser#14]
when I disconnect a bluetooth device, the "system" employs some alternative default device. So far so good. I wonder: would it be possible to let the extension automatically choose the last explicitly chosen device (again) once that device becomes available again?

**Comment by wvengen** [comment]
Wouldn't this be a pulseaudio feature? In my experience it already supports such a thing (including the notion of a fallback device, with buttons for it in the volume control).

**Comment by ilippert** [comment]
pulseaudio, yes, uses the reconnected device when it becomes available again.
however, the extension does not mark the reconnected device as the active/selected one. And the volume control only operate on the active/selected one.
I am not sure, of course, whether it is the "job" of this extension to look into this - sorry if this is out of place.

**Comment by wvengen** [comment]
Thanks for clarifying! Do you mean that the extension does not show the reconnected device as active?
I'm not really sure how the volume control (which I think is handled elsewhere than in this extension, which only handles selecting an ouput / input) decides which volume to change, I think this might be possible to change using gconf (`/desktop/gnome/sound` perhaps? -- from [here](https://wiki.ubuntu.com/Hotkeys/Troubleshooting)), not sure though.

**Comment by ilippert** [comment]
yes, the extension does not show the reconnected device as active (marked with the check mark).

the volume control does effectively control the volume of the device that is marked as active, rather than the one pulseaudio uses. 

As it seems, pulseaudio overrides the extension.
In that case: I wonder whether the extension could query pulseaudio to check which device it is using and adjust accordingly.

**Comment by wvengen** [comment]
I would consider it a bug when the extension doesn't follow pulseaudio's idea of active device.

**Comment by ilippert** [comment]
@kgshank would you agree with considering this a bug?

**Comment by kgshank** [comment]
Didn't get a chance to look into the extension for long. 

First of all the extension relies on gvc for all device info. Actually the extension is just meant to be a shortcut for the Sound settings device selection in gnome control center. So, this would be a bug if you see the device marked as active in control center and not in the extension. But if the behaviour is the same in gnome control center, then it cannot be considered as a bug. Please verify and let me know and I will work on it.

**Comment by ilippert** [comment]
The extension perfectly mirrors the settings in the gnome control center. So both of these do not represent necessarily the actual sound output.
