### ISSUE TITLE
Hide sound device doesn't filter correctly

### ISSUE THREAD

**Issue by TheBlackKoala** [kgshank/gse-sound-output-device-chooser#141]
Please provide the shell and extension information. It will be easier for me to understand the issue without too many unnecessary questions

**Describe the bug**
When even a single device is set to "Hide" the extension will filter out a lot of the devices but when there are only default they will all be shown correctly. It seems to me that the filter on one device will catch a lot of other devices which is not intended.

**Extension Information**
GNOME Shell 3.38.3
Latest from git
README
Arch Linux

**Error / Journal messages**
None. Devices just not showing up as they should

**Comment by kgshank** [comment]
@TheBlackKoala  can you send the screenshot of the extension preferences with the devices that you have selected "Hide"

**Comment by TheBlackKoala** [comment]
Here are two screenshots - one with all my current devices shown and one where i am hiding a single "Analog Output - Built in Audio" which also hides the "Analog Output - NAD USB Audio" which was not supposed to be hidden.
![Screenshot from 2021-02-24 12-13-29](https://user-images.githubusercontent.com/8694231/108992634-d1fc9f80-7699-11eb-8658-b3c59f50a19a.png)
![Screenshot from 2021-02-24 12-13-00](https://user-images.githubusercontent.com/8694231/108992645-d45ef980-7699-11eb-8954-8e4c1369d110.png)

**Comment by scr4bble** [comment]
I have similar problem. For me it seems the menu isn't refreshed when it should be. Then the only way to choose correct device is going through the native sound settings and click the device there.
Possible reasons - refresh of the devices list for extension isn't always triggered or filter doesn't work correctly.

**Comment by kgshank** [comment]
I am rewriting the extension completely to avoid memory issues caused by mishandling of C pointers. I will release a working version soon. Please bear with the delay!!

**Comment by kgshank** [comment]
@TheBlackKoala Please retest with the new git version and let me know if the issue still exists

**Comment by TheBlackKoala** [comment]
@kgshank still same erroneous behaviour

**Comment by TheBlackKoala** [comment]
Here is the output from the log and the helper - after i had hidden and unhidden a few of the speakers.
I also noted that after unhiding the speakers they showed up twice in the list - though that seems pretty inconsequential.
[logoutput.txt](https://github.com/kgshank/gse-sound-output-device-chooser/files/6175309/logoutput.txt)
[output.txt](https://github.com/kgshank/gse-sound-output-device-chooser/files/6175310/output.txt)

**Comment by kgshank** [comment]
Hi @TheBlackKoala, the messages don't match the current code. Can you try to update from git once again?

**Comment by TheBlackKoala** [comment]
@kgshank i did a wipe/clone (don't know why a regular pull didn't work) and from what i can tell it works - when i hide Analog Output - Built-in Audio it does not hide Analog Output - NAD USB Audio and vice versa - thank you very much for your work on this awesome extension! :D
