### ISSUE TITLE
Extension is always initializing..

### ISSUE THREAD

**Issue by leoheck** [kgshank/gse-sound-output-device-chooser#142]
Extension is always initializing.. 

![image](https://user-images.githubusercontent.com/1277920/109680508-539d7300-7b5b-11eb-87e9-d7f55f20338e.png)

**Comment by NicolasGoeddel** [comment]
I have the same issue since the last update of the extension on Ubuntu 20.10 with Gnome 3.38.2.

**Comment by AJJLagerweij** [comment]
The same here on Ubuntu 20.04 with 3.36.8. Can you reproduce the issue, or what information should we provide to help?

**Comment by NicolasGoeddel** [comment]
At the moment it works. I don't know exactly when this happens.

**Comment by leoheck** [comment]
It happens every time you (re)start the computer

**Comment by ENPark** [comment]
+1

**Comment by leoheck** [comment]
Maybe it is because it is not storing or accessing a preview value. Or because it is failing to fall back to default items.

**Comment by timnolte** [comment]
Yeah, this has been happening to me too. I'm on Pop!_OS 20.10, Gnome 3.38.3

**Comment by kgshank** [comment]
I am rewriting the extension completely to avoid memory issues caused by mishandling of C pointers. I will release a working version soon. Please bear with the delay!!

**Comment by Asitis** [comment]
On Ubuntu it works if you press ALT+F2 and type 'r' to restart the desktop enviorment; after this the module works like expected!

**Comment by kgshank** [comment]
The new version is updated in the git. Please install from git and let me know if you find this issue again or any other error

**Comment by AJJLagerweij** [comment]
Thanks for the awesome work. I'll be testing it for a week and get back to you next weekend.
I haven't seen any problems yet, though ♥.

**Comment by artscoop** [comment]
Oh Gopi @kgshank it seems you dit it, the latest version of the extension works again on my computer (has not happened for the last two months so I consider it fixed). We have to wait for the others' experience, but to me it looks very good. Thanks!

**Comment by leoheck** [comment]
True, it is working for me too.

**Comment by NicolasGoeddel** [comment]
Seems also to work for me.

**Comment by leoheck** [comment]
Alright, since it is working I will close this for now. Thanks guys.

**Comment by boistordu** [comment]
It is happening again under fedora 33...

Also I would like to add that every time I tried to update your app it s going into error mode and I need to reboot the pc to actually make it work.

**Comment by Asitis** [comment]
Same! Every update it breaks, every second update it works again. My pro
tip: don't update it as long as it works.

**Comment by kgshank** [comment]
The fixes are released in git. sorry for the issues.

**Comment by Ileca** [comment]
I have the same problem but only for the input devices (I have no input device connected so it doesn't impact me).
I am using v40 on Gnome 3.36.

**Comment by thesmallcreeper** [comment]
@Ileca #218 fixed this issue. Get latest git

**Comment by Ileca** [comment]
Nice. Working fine. Thank you.
