### ISSUE TITLE
Port Settings split in input and output devices

### ISSUE THREAD

**Issue by leoheck** [kgshank/gse-sound-output-device-chooser#145]
I am using the latest version from git.

Is it possible to see have info about input/output on this list? A simple column with this info would be nice to have.

![image](https://user-images.githubusercontent.com/1277920/111888244-919ef180-89b9-11eb-9919-2e6c0fca1a4b.png)

**Comment by kgshank** [comment]
Done!

**Comment by leoheck** [comment]
Wow. Thanks, let me check here.

**Comment by leoheck** [comment]
Oh! This helps a lot. Thank you.
![image](https://user-images.githubusercontent.com/1277920/111910793-93ac9300-8a41-11eb-99ac-06a4d10114a5.png)
