### ISSUE TITLE
Newest version stuck on "Extension Initializing"

### ISSUE THREAD

**Issue by FoamyGuy** [kgshank/gse-sound-output-device-chooser#152]
I was prompted yesterday to install a new version of this extension and did so using extensions.gnome.org. 

After booting up this morning with the newest version the extension no longer seems to work. It is stuck saying "extension initializing" and has not completed after several minutes. 

![image](https://user-images.githubusercontent.com/2406189/112838983-46dd4380-9063-11eb-84c9-a64ebea4db18.png)

I am never able to successfully update this extension from the gnome.org page, whenever new versions are available if I go to the page and click update it will think for a minute and then show "ERROR". Typically things go back to working normally after I reboot. 

The page does not currently report an error: 
![image](https://user-images.githubusercontent.com/2406189/112839252-958add80-9063-11eb-82ea-1a1a0231b652.png)

But the extension is still stuck with this initializing message, not allowing me to select devices.

The settings page inside of tweaks seems normal:
![image](https://user-images.githubusercontent.com/2406189/112839379-c408b880-9063-11eb-8d7e-6b02e6d32f98.png)

Is there any way that I can get this extension back to functional today? or anything I can provide to assist in troubleshooting these issues?

**Comment by simonardejr** [comment]
Exactly same issue here. Updated yesterday and got stuck on "Extension Initializing".

**Comment by kgshank** [comment]
Update in extensions.gnome.org removed, v38 available in git if you want to test. 

Same as #149. So closing for now.
