### ISSUE TITLE
What are the python dependencies?

### ISSUE THREAD

**Issue by leoheck** [kgshank/gse-sound-output-device-chooser#154]
What are the python dependencies?

![image](https://user-images.githubusercontent.com/1277920/114032341-99ccad00-9852-11eb-8d42-4f6063a893dd.png)

Do you mean, the Python language or a specific Python package? Or maybe you are talking about Python 2? This is what I have available.
![image](https://user-images.githubusercontent.com/1277920/114032502-bd8ff300-9852-11eb-9857-e323e384779a.png)

**Comment by leoheck** [comment]
The plugin is not working for me anymore. I would like to install the missing dependencies. How can I do to see the dependencies needed?

**Comment by kgshank** [comment]
Anything is fine, python V2 or V3, only the python interpreter is needed. Even if python is not available, the extension will fallback to old ways of identifying the port information. So it shouldnt be a problem.

Your error should go away after you restart your gnome session. This seems to be a common error when updating extensions via extensions.gnome.org

**Comment by leoheck** [comment]
I see, thanks for the answer @kgshank I thought I have restarted the computer last night but it looks like it didn't do it. I will get back in a couple of minutes to close this after restarting my session.
