### ISSUE TITLE
[Feature Request] Hide Unavailable Profiles

### ISSUE THREAD

**Issue by hvitoi** [kgshank/gse-sound-output-device-chooser#156]
I have two bluetooth speakers which show many sink profiles, but most of them are unavailable
I'd be great to have an option to toggle on/off the visibility of unavailable profiles

![Screenshot from 2021-04-08 13-18-34](https://user-images.githubusercontent.com/44772383/114061950-59c6f380-986d-11eb-8dd5-1c98b1f104d2.png)
![image](https://user-images.githubusercontent.com/44772383/114062466-f12c4680-986d-11eb-82d2-b0966219ed04.png)

Moreover, it'd be nice to be able to set a short alias for each profile. As it is now they have very long, unnecessary names.
For example:
   - A2DP: AAC
   - A2DP: SBC
   - HSP/HFP

**Comment by kgshank** [comment]
It should be possible, I will try to implement

**Comment by cenktaskin** [comment]
Bump!
