### ISSUE TITLE
When using a dark theme, profiles not selected are invisible

### ISSUE THREAD

**Issue by 7RST1** [kgshank/gse-sound-output-device-chooser#157]
When using a dark theme, only the devices and selected profiles stays black, the others are white and invisible in front of white background. The options also shows when hovering.

I don't know if this is an issue with every dark theme, but at least it happens with orchis-dark. I'm using Pop OS 20.10 with Wayland enabled.

![bilde](https://user-images.githubusercontent.com/16783057/114063815-4b8ecc80-9899-11eb-9066-878f969336c9.png)

**Comment by kgshank** [comment]
It seems to be a problem with the theme, as I don't control the theme elements (except the bullet for selected device/profile) within the extension. I tested with different themes available within default POP os and other distros that I generally test and it behaves normally. Please check with the theme developer.

**Comment by 7RST1** [comment]
Okay, will check further with orchis-dark.
