### ISSUE TITLE
Extension prevents login

### ISSUE THREAD

**Issue by m1pl** [kgshank/gse-sound-output-device-chooser#160]
This is a critical issue.

I just spent over an hour identifying the problem: When using new profile identification, the extension depends on python. If for any reason python is in PATH, but not pointing to a valid python executable, the extension blocks the login. After a reboot and login, I would just see a black screen and be able to move the cursor, nothing else.

In my case, `/usr/bin/python` is a symlink which became broken due to an issue with pyenv. After a reboot the aforementioned issue arised.

Running Ubuntu 21.04.

**Comment by kgshank** [comment]
I tried creating a broken symlink in /usr/bin and for the extension fails normally and switches to old method for identifying the profile. I can login normally. 

Also, I call the GLIB APIs to execute the command, if they block the session when the executable is missing or broken, then obviously the extension cannot get the control back to fail gracefully. I cannot verify the entire PATH entries for the python executable in the extension, as it is not practical for me.  If you can duplicate the issue again, please create an issue with Gnome team.

**Comment by m1pl** [comment]
I got it so far that when I would enable the extension whith the broken python symlink, the system would instantly freeze. I'll check GLIB, thanks.
