### ISSUE TITLE
[BUG] Impossible to unhide ports in settings

### ISSUE THREAD

**Issue by kubrickfr** [kgshank/gse-sound-output-device-chooser#162]
Using revision 610760f, on Gnome 40.1, Arch Linux.

- It is impossible to unhide ports once the have been selected
- They are radio buttons instead of check boxes

![image](https://user-images.githubusercontent.com/2634188/118274515-8356e880-b4c5-11eb-9877-baa4a5e649ba.png)

**Comment by kubrickfr** [comment]
I just realised that quite a vicious UI thing was happening:
![image](https://user-images.githubusercontent.com/2634188/118275458-b9e13300-b4c6-11eb-9b25-2d29a72d7c48.png)
There is in fact a horizontal scroll-bar but it really wasn't obvious, I had to open the UI definition files in glad to see that.
Maybe we can do things differently here? IDK

**Comment by kgshank** [comment]
There is a Default column to the right. It seems to be hidden in your case for some reason. Resize the dialog should fix the issue temporarily. Also, the latest git version is still not fully tested, so you can expect some rough edges.
