### ISSUE TITLE
[BUG] The highlighted profile for a device is often not the current profile

### ISSUE THREAD

**Issue by dhwalker** [kgshank/gse-sound-output-device-chooser#163]
After clicking on the current device to see its available profiles, the device's current profile is often not the highlighted profile. Regarding the log messages below...

- **08:15:27** - I selected A33's A2DP profile. The extension's profile highlighting was correct.
- **08:15:35** - I selected A33's HFP profile. The extension still highlighted the A2DP profile. FYI, the system Sound Settings (correctly) showed HFP.

**Extension Information**
* Gnome 40
* Extension Version 38
* Installed from extension.gnome.org
* openSUSE Tumbleweed (20210511)

**Error / Journal messages**
* Enable Log messages in extension preferences and share the output of  `journalctl -r | grep SDC`
May 14 08:15:35 homelap7.WalkerStreet.info gnome-shell[3602]: SDC Debug: Activated: 13:Headset - A33
May 14 08:15:35 homelap7.WalkerStreet.info gnome-shell[3602]: SDC Debug: Activated:- 13
May 14 08:15:35 homelap7.WalkerStreet.info gnome-shell[3602]: SDC Debug: Activated:- 14
May 14 08:15:35 homelap7.WalkerStreet.info gnome-shell[3602]: SDC Debug: Active Profile:a2dp_sink
May 14 08:15:35 homelap7.WalkerStreet.info gnome-shell[3602]: SDC Debug: i am setting profile, handsfree_head_unit:Headset:headset-output
May 14 08:15:35 homelap7.WalkerStreet.info gnome-shell[3602]: SDC Debug: Activating Profile:14handsfree_head_unit
May 14 08:15:27 homelap7.WalkerStreet.info gnome-shell[3602]: SDC Debug: Active Profile:a2dp_sink
May 14 08:15:27 homelap7.WalkerStreet.info gnome-shell[3602]: SDC Debug: i am setting profile, a2dp_sink:Headset:headset-output
May 14 08:15:27 homelap7.WalkerStreet.info gnome-shell[3602]: SDC Debug: Activating Profile:14a2dp_sink

**Comment by kgshank** [comment]
I will check this issue

**Comment by janvonde** [comment]
Any news on this? The same happens for me for quite some time now. Thanks for your effort @kgshank by the way. I love this extension and it makes my life much easier! :slightly_smiling_face:

**Comment by thesmallcreeper** [comment]
I was having a quick look over at source code (haven't tried to replicate it myself yet).
Even tho it shows wrong profile, after like 2 seconds doesn't it show the correct one?
If this is case maybe it a race condition

**Comment by janvonde** [comment]
Hi @thesmallcreeper,

my problem is not a race condition. My problem is, that it is somehow mixed up. I switch between three output devices:
* Monitor
* Headset via cable
* Bluetooth headset

The only thing that always works is the Monitor via HDMI. But when I switch over to the Bluetooth headset it sometimes does'n work. I have to choose the Headset via cable or another, completely unused S/PDIF output to get things out of the bluetooth headset. When I switch to Gnome settings and change the audio output device there it is always correct.

The extension used to work fine, but I think with the update to Gnome 40 this behaviour started appearing.


Thanks for your time!

Jan :-)

**Comment by thesmallcreeper** [comment]
@janvonde From my understanding your problem doesn't have to do with selecting profiles but with selecting devices. Maybe this is another issue :/ . Also if you are able to find which exactly commit did the regression you can help a lot to find the problem.

About this issue @dhwalker your feedback will be helpful :)

**Comment by dhwalker** [comment]
I don't think I've ever seen the wrong device displayed, only the wrong highlighted profile. I rarely use anything other than the internal speaker or one of a couple of bluetooth devices, though.

Also, the profile highlighting doesn't seem to correct itself after a few (or even several) seconds. Even closing the gnome-shell menu, reopening it, and clicking on the device to see its selected profile does not highlight the right profile.

**Comment by thesmallcreeper** [comment]
Right now when we use profiles we setup a timer over here

https://github.com/kgshank/gse-sound-output-device-chooser/blob/9d16a9dd3cebcd95436f76cd84fcefbff5fbd5cf/sound-output-device-chooser%40kgshank.net/base.js#L297-L312

According to this: https://gjs-docs.gnome.org/glib20~2.66.1/glib.timeout_add
In order to keep the timer alive we should `return true`

To begin in the below code if submenu is not open we don't return true so we kill the timer.
https://github.com/kgshank/gse-sound-output-device-chooser/blob/9d16a9dd3cebcd95436f76cd84fcefbff5fbd5cf/sound-output-device-chooser%40kgshank.net/base.js#L523-L537

Moreover I believe we can avoid using timers.
We can `connect` to signal 'open-state-changed' of the `this.menuItem.menu` and do the refresh of profiles right when open the submenu. 

Not 100% sure if this gonna fix the problem but it will be an improvement :tada: 

@kgshank give me your opinion on the matter. I will do the coding part of things.

**Comment by kgshank** [comment]
@thesmallcreeper Yes instead of the timer, we can switch to signal 'open-state-changed'.  Please if possible, go ahead with the coding.  In general Bluetooth profiles are always tricky to handle with the extesion. Sometimes gnome api's don't report the proper profile even though the profile change is actually completed. The alternate option is to query using pulseaudio api's , I am not sure about the feasibility though.

**Comment by thesmallcreeper** [comment]
@dhwalker Pull request #177 should do the trick. Can you check? I tested on my bluetooth device and the highlighting works :)

**Comment by dhwalker** [comment]
Fix issue #163 is better, but one of the three Bluetooth profiles (HSP) is not displayed. Selecting either A2DP or HFP works as expected, but it's not possible to select HSP, as it's not displayed. Selecting HSP in Sound Settings leaves gse-sound-output-device-chooser's highlighting unchanged (either A2DP or HFP, depending on what was previously selected).

**Comment by thesmallcreeper** [comment]
@dhwalker Indeed I also came across this issue, however iirc changing profile to HSP from gnome-settings had no effects. I mean that when I was switching from HFP to HSP the audio quality was still garbage while when I was switching from A2DP to HSP the quality was still good. I mean that maybe gnome-settings report HSP but has no effect when it is chosen. So maybe we are good from our side and this is a gnome-settings issue.

Let me know if this is the behavior of HSP in your system.
Thank you! :)

**Comment by dhwalker** [comment]
I believe the difference between HSP and HFP has to do more with features that are enabled (e.g., adjust volume, answer call) than the audio quality. (See [https://en.wikipedia.org/wiki/List_of_Bluetooth_profiles#Hands-Free_Profile_(HFP)](https://en.wikipedia.org/wiki/List_of_Bluetooth_profiles#Hands-Free_Profile_(HFP)) ) The difference can be important for applications like Zoom and Skype.

**Comment by thesmallcreeper** [comment]
@dhwalker Sorry maybe I failed to get the message across. 

I am not criticize by any way the HSP protocol.
What I mean is that when in my case HSP over at gnome-settings is like a ghost profile. When I move to it from HFP or A2DP nothing changes. HFP and A2DP are like night and day in quality and when I go HFP->HSP HFP quality is still there, when I go A2DP->HSP A2DP quality is still there. I guess that choosing HSP in one of two case at least should had a change in quality of audio.

**Comment by dhwalker** [comment]
(I didn't think you were criticizing.)

I think the issue is that Bluetooth profiles are not necessarily audio profiles; they may (or may not) affect audio. In this case, I think you're right that HSP and HFP both have the same audio quality. HSP and HFP do differ, though, in the non-audio features they provide to an application. In my limited testing, For example, in my limited testing, I've been able to get Zoom to work with HFP but not HSP, so there must be some difference. (FYI, while A2DP has better quality, it does not allow for use of the microphone, so isn't useful for video/audio conferencing applications like Zoom or Skype.) This, of course, means that, at least for now, I don't care about HSP support personally, but it's likely that someone who uses some other application does care.

So, I hope you will support setting all three bluetooth profiles, even though they don't have three distinct effects on sound output.

Thanks for sticking with this issue. I appreciate the time you're spending.

**Comment by thesmallcreeper** [comment]
In my system (as yours) the extension shows 2 profiles while gnome-settings 3
Did some searching previously and this is what I found.

Running `pa_helped.py` (`/sound-output-device-chooser@kgshank.net/utils/pa_helped.py`) I get the following output:
```
...
"2": {
	"index": "2",
	"profiles": [
	    {
		 "name": "headset_head_unit",
		 "human_name": "Headset Head Unit (HSP)",
		 "available": 0
	    },
	    {
		 "name": "a2dp_sink",
		 "human_name": "High Fidelity Playback (A2DP Sink)",
		 "available": 1
	    },
	    {
		 "name": "handsfree_head_unit",
		 "human_name": "Handsfree Head Unit (HFP)",
		 "available": 1
	    },
	    {
		 "name": "off",
		 "human_name": "Off",
		 "available": 1
	    }
	],
	"alsa_name": "",
	"card_description": "Voyager PRO+",
	"name": "bluez_card.00_23_7F_E1_5B_52",
...
```

So it finds HSP but in my case it not available so it doesn't add it to the list.

https://github.com/kgshank/gse-sound-output-device-chooser/blob/9d16a9dd3cebcd95436f76cd84fcefbff5fbd5cf/sound-output-device-chooser%40kgshank.net/convenience.js#L316-L330

If we want to also report not available profiles (HSP for example) we just need to remove line 323 above, but do we really want to? I think not.
In my previous replies I was trying to explain that choosing HSP at Settings might be a "lie". According to Pulseaudio it is not available in my case.

Now about the features of HSP I see that someone would like to have its features but for example in my device (or yours maybe) it is not available... I guess if someone's devices indeed have HSP it should report it as available (or pulseaudio has a bug or something on reporting availability?)

@dhwalker I think now you start see what is going on under the hood.
Btw thank you for your appreciation :) .

**Comment by dhwalker** [comment]
Interesting. My device claims that it supports HSP (https://pl.factoryoutletstore.com/details/495214/voyager-5200.html?category_id=97148&catalogitemid=450371), but pa_helped.py says it's not available:

          "1": {
               "index": "1", 
               "name": "bluez_card.E4_22_A5_05_A5_F1", 
               "card_description": "PLT V5200 Series", 
               "profiles": [
                    {
                         "available": 0, 
                         "human_name": "Headset Head Unit (HSP)", 
                         "name": "headset_head_unit"
                    }, 
                    {
                         "available": 1, 
                         "human_name": "High Fidelity Playback (A2DP Sink)", 
                         "name": "a2dp_sink"
                    }, 
                    {
                         "available": 1, 
                         "human_name": "Handsfree Head Unit (HFP)", 
                         "name": "handsfree_head_unit"
                    }, 
                    {
                         "available": 1, 
                         "human_name": "Off", 
                         "name": "off"
                    }
               ], 
               "alsa_name": "", 

I suspect you're right that this is likely a pulseaudio issue, not gse-sound-output-device-chooser. I'm willing to say this is resolved if you are.

**Comment by thesmallcreeper** [comment]
@dhwalker Yeah this extension doesn't have the best relations with Pulseaudio :P haha
By the way, there is an upcoming mixer named Pipewire which tries to take the place of Pulseaudio. Has compatibility with PA interface and modules etc.. It might have support for HSA is you ever need it.

I also think issue is mostly resolved, just lets wait for the pull request to merge.
We managed to make the extension a little better! Yay! :tada:

**Comment by dhwalker** [comment]
Thanks, Creeper! 🎉
