### ISSUE TITLE
[BUG] Can't change settings in "Port Settings"

### ISSUE THREAD

**Issue by iyyel** [kgshank/gse-sound-output-device-chooser#170]
**Describe the bug**
Unable to change any settings in "Port Settings". When a device is hovered upon, all three radio buttons are hightlighted (example: https://i.imgur.com/zd59hDJ.png), and clicks are not registered, meaning I can't hide devices, for example.

**Extension Information**
* Shell Version: 40.1.0
* Extension Version (Leave blank, if not sure): 38
* Install method (extension.gnome.org, AUR, github etc.): extension.gnome.org (using Gnome Extensions flatpak on the system)
* OS: Fedora 34 (Workstation Edition)

**Error / Journal messages**
* Enable Log messages in extension preferences and share the output of  `journalctl -r | grep SDC`: Empty.

**Comment by iyyel** [comment]
Welp. Issue was fixed by randomly moving the cursor around in the settings screen, and suddenly I was able to change the port settings. Not sure issue is directly related to the extension, honestly.

I'll let @kgshank decide whether to keep it open or not.

**Comment by thesmallcreeper** [comment]
To add to the issue from my experience the problem sum up as this:
While scrolling to right the hitboxes of toggles start to shift to the left until they aren't working.

In other words,
when a toggle is already on your screen (for example when fullscreen) toggle works just fine.
when you scroll a little to the right the hitbox of toggle is kinda to the left of its actual position.
