### ISSUE TITLE
Does not change device if Rhythmbox is open

### ISSUE THREAD

**Issue by BoBeR182** [kgshank/gse-sound-output-device-chooser#18]
I cannot change the device profile from Headphones to Speakers, or vice versa if Rhythmbox is running.

Expected behaviour is to change outputs, actual behaviour menu closes before when I click to expand all devices.

**Comment by kgshank** [comment]
I can change the outputs while rhythmbox is running.  Can you change the outputs with other applications running ?

**Comment by BoBeR182** [comment]
Yes I can, VLC does not interfere nor Steam games.

**Comment by BoBeR182** [comment]
Closing, turns out it's a bug with Gnome, when they menu height exceeds the display resolution the menu will not show. Thus having VLC open caused the media player shortcuts to add extra pixels.
