### ISSUE TITLE
Gnome 41 Support?

### ISSUE THREAD

**Issue by Scotty-Trees** [kgshank/gse-sound-output-device-chooser#182]
Greetings,

Gnome 41 was released this month and I was wondering if/when the extension will be updated? Thank you for your time and thank you for making an amazing extension I couldn't live without! Cheers

**Comment by thesmallcreeper** [comment]
#181 :)

**Comment by Scotty-Trees** [comment]
Ah, my apologizes I didn't see this thread was already posted! You may close this issue if you like and refer to the other one for this issue, thank you for your time and quick reply!

**Comment by vwbusguy** [comment]
It looks like it was merged but hasn't been published yet, so it still won't update/start for me in Gnome 41 on Fedora 35 Beta.  

![image](https://user-images.githubusercontent.com/5474941/135665430-364f8213-0418-4451-a692-5d5056ee4805.png)

**Comment by laichiaheng** [comment]
Why can't extensions support the latest Gnome before they released the latest stable version?

**Comment by kgshank** [comment]
@laichiaheng  I don't have time to prepare an unreleased Gnome environment to test the extension. Unfortunately I have a job and a family. So I couldn't spend time in these "important" stuff. Please don't comment like you are entitled. Yes I know Gnome 41 is available and I will try to push something as soon as possible. For you, it's just matter of supporting Gnome 41. For me it's testing in probably 4-5 Gnome versions that still many people use. So my answer to you is , "It will be available when it's ready"

**Comment by artu72** [comment]
> For me adding "41" to the list of versions in the metadata.json file, as well as renaming the uiFileSuffix value in prefs.js from 40 to 41 - and then restarting the Gnome Shell (Alt+F2 -> "r" -> Enter) - made the extension work fine. Hope this helps someone else, until the extension gets updated to support v.41 officially.
> 
> To the developer - a BIG thank you :)

Consider also renaming the file prefs-dialog40.glade to prefs-dialog41.glade

**Comment by kgshank** [comment]
Working on a new release, will push something this week

**Comment by Scotty-Trees** [comment]
Extension now has proper Gnome 41 support. Thanks to everyone that helps work on and maintain this awesome extension, thank you all so very much! :)
