### ISSUE TITLE
[BUG] 

### ISSUE THREAD

**Issue by Fran-FC** [kgshank/gse-sound-output-device-chooser#191]
The extension breaks in fedora 35 and gnome 41

**Comment by thesmallcreeper** [comment]
Are you using git version?
If not test with latest git version which provide support for gnome 41. Many other issue tickets report this problem. Have a look.

**Comment by dquark** [comment]
You can edit  _~/.local/share/gnome-shell/extensions/sound-output-device-chooser@kgshank.net/metadata.json_ and add "41" in  shell-version, like this:
`"shell-version": [                                                                                
        "3.34",                                                                                         
       "3.32",                                                                                         
       "3.36",                                                                                         
       "3.38",                                                                                         
      "40",                                                                                           
       "41"                                                                                            
     ], `

**Comment by kgshank** [comment]
The git version works in v31 without issues. New release added in extensions.gnome.org as well

**Comment by kgshank** [comment]
Please report any issues to the tracking ticket #195 for 41
