### ISSUE TITLE
[BUG] Microphone volume icon disappeared in version 41.39 [Gnome 41]

### ISSUE THREAD

**Issue by ShrirajHegde** [kgshank/gse-sound-output-device-chooser#193]
**Describe the bug**
Extension installed from github doesn't work on gnome 41 while version from extensions.gnome.org works fine with 
`gsettings set org.gnome.shell "disable-extension-version-validation" true ` set

**Extension Information**
* Shell Version - 40.1
* Extension Version (Leave blank, if not sure) - "version": 38
* Install method (extension.gnome.org, AUR, github etc.) - Gnome extensions and github
* OS - Fedora 35

**Error / Journal messages**
* Enable Log messages in extension preferences and share the output of  `journalctl -r | grep SDC`
**None**

Screenshots:

GitHub:
![image](https://user-images.githubusercontent.com/66936172/141152563-f5f28d4c-3e10-439a-b7a0-9e5c36d9613e.png)

Gnome Extensions:

![image](https://user-images.githubusercontent.com/66936172/141153049-8c6a06ca-ef98-4bd3-961c-aa836d3af57c.png)

**Comment by thesmallcreeper** [comment]
@ShrirajHegde Can you give a try to provide some error logs? Make sure you have enabled Log messeges and restart the session. Maybe try `journalctl -r | grep gnome-shell` instead and find what problem gnome-shell face. Thank you in advance.

**Comment by ShrirajHegde** [comment]
> Make sure you have enabled Log messeges and restart the session.

How do I check this??

**Comment by linuxnow** [comment]
It works as expected in Gnome 4.1.
It would be nice to update Gnome Extensions.

**Comment by thesmallcreeper** [comment]
@ShrirajHegde 
1. Open "Extensions" app. 
![image](https://user-images.githubusercontent.com/9092001/141290554-a14f19fd-3924-486b-8187-1587eb533654.png)

2. Click on gear-settings icon of "Sound Input and Output Device Chooser". Prefs will open.
![image](https://user-images.githubusercontent.com/9092001/141290868-5a4319fd-2c6b-471d-a41b-962615bbf1fa.png)

3. Down down in the "Miscellaneous" session make sure the "Enable Log messages" is enabled.
![image](https://user-images.githubusercontent.com/9092001/141291113-73f109ea-afd3-4867-aa9e-c9cb08363836.png)

**Comment by kgshank** [comment]
I tested in V41 and works as expected. New release uploaded in extensions,gnome,org and should be available after review

**Comment by ShrirajHegde** [comment]
@kgshank 

I have updated to the latest version from extensions.gnome.org, and it has stopped working, 

Now I can see this in log

```
JS LOG: SDC Debug: JS LOG:_UI file receive and load: /home/user/.local/share/gnome-shell/extensions/sound-output-device-chooser@kgshank.net/ui/prefs-dialog40.glade
```
It worked fine before the update for me.

**Comment by ShrirajHegde** [comment]
I did a reinstall, now the extension works, but the mic volume icon seems to have disappeared.

![image](https://user-images.githubusercontent.com/66936172/141818829-16a4acd6-2511-47bf-b163-4988324824d5.png)

Reinstalling the previous version from a backup brings it back 

![image](https://user-images.githubusercontent.com/66936172/141819311-ac74b194-058a-4485-845c-a6c58e4e8094.png)

**Comment by ShrirajHegde** [comment]
Gnome extension auto-updates it, I had to uninstall gnome-extensions app.

Is anyone else facing this problem?

**Comment by thesmallcreeper** [comment]
@ShrirajHegde #197

**Comment by ShrirajHegde** [comment]
So can we get it as a setting? Something like  "Hide microphone icon when idle"

**Comment by ShrirajHegde** [comment]
> @ShrirajHegde #197

That is a great feature. Thanks.

**Comment by thesmallcreeper** [comment]
> So can we get it as a setting? Something like "Hide microphone icon when idle"

Won't be hard but not motivated enough right now :disappointed:
