### ISSUE TITLE
RFE: support input-devices too

### ISSUE THREAD

**Issue by MagicFab** [kgshank/gse-sound-output-device-chooser#2]
Thank you for this useful extension.
It would be nice to have the same kind for control for input devices. I often used external microphones, internal ones, or the webcam's integrated one and would like to be able to swtich control/mute easily.

**Comment by stefanmaric** [comment]
+1

**Comment by kgshank** [comment]
Sorry guys couldn't set time to explore. Well try to include soon

**Comment by linuxturtle** [comment]
+5  This is an awesome extension, would be perfect if it also let you choose/control inputs.

**Comment by stefanmaric** [comment]
I will invite a beer (10 USD) to anyone with a pull request that successfully implements both, input and output devices chooser for gnome shell 3.18 and 3.20. :)

**Comment by kgshank** [comment]
Expect an update in the coming week. I have implemented option for input devices as well. Now working on some other additional feature requests.

**Comment by kgshank** [comment]
Uploaded new version to extension.gnome.org . The new version has support for input devices  as well

**Comment by stefanmaric** [comment]
> Uploaded new version to extension.gnome.org . The new version has support for input devices as well

:boom: It works smoothly as far as I've been able to test, on gnome shell 3.18.

PD: The beer invitation still stands. :)

**Comment by kgshank** [comment]
@stefanmaric Thanks for the offer. Enjoy the beer on my behalf. Let me know if you face any issues with the extension
