### ISSUE TITLE
3.22 Update please

### ISSUE THREAD

**Issue by PeteLawler** [kgshank/gse-sound-output-device-chooser#20]
Debian Testing is now on Gnome 3.22. If you could update it'd be super appreciated.

**Comment by kgshank** [comment]
Thanks for the interest. I am using Manjaro, and 3.22 is not available yet. I need to update from arch repos. I will update after testing in the coming week.

**Comment by PeteLawler** [comment]
So as of today's Stretch update, things seem working again...
