### ISSUE TITLE
Propably a spelling bug at extension.js

### ISSUE THREAD

**Issue by thesmallcreeper** [kgshank/gse-sound-output-device-chooser#203]
https://github.com/kgshank/gse-sound-output-device-chooser/blob/dcc9d289d489e49178e6ce427dc4a316ef688ab8/sound-output-device-chooser%40kgshank.net/extension.js#L220

https://github.com/kgshank/gse-sound-output-device-chooser/blob/dcc9d289d489e49178e6ce427dc4a316ef688ab8/sound-output-device-chooser%40kgshank.net/extension.js#L222

Shouldn't that be `this._outputInstance.menuItem.actor.visible` and `this._inputInstance.menuItem.actor.visible`?
Howeven, the whole thing works :P

**Comment by kgshank** [comment]
yes, i introduced it only to avoid to looking at the property when the menuitem.destroy() is being called, as I was not really sure,whether event chain for visibility during destroy will have a chance to access the property. I will update the code. Thanks for the feedback

**Comment by thesmallcreeper** [comment]
@kgshank Still I think you got it wrong, not just `.visible` but `.actor.visible` is the correct one.

**Comment by thesmallcreeper** [comment]
hmmm.. doesn't affect something however...

https://gitlab.gnome.org/GNOME/gnome-shell/-/blob/main/js/ui/popupMenu.js#L107
`actor` is just a getter

**Comment by kgshank** [comment]
yes, actor is just a getter for the instance itself now, but it was a separate property in older gnome versions. I am not sure whether we still support those versions, but its better to add that. I will make the changes soon
