### ISSUE TITLE
Cannot use the extension - fails to reinstall

### ISSUE THREAD

**Issue by izurdo** [kgshank/gse-sound-output-device-chooser#205]
Hi,

The extension is not working properly (it worked perfectly during one year approx, now I cannot choose my microphone and it draws the items a little differently), my OS is redhat 8.4 and it runs the gnome version 3.32.2.

The error it shows on the "Extensions" Gnome app is:
"TypeError: this.item.notify is not a function"

I have tried removing it and reinstalling, even removing, rebooting the laptop, and installing again, but it does not work, when the extension is installed it shows an "ERROR" at the website extensions.gnome.org

Would you please help to fix this issue?

Thanks
![extensionnotworking](https://user-images.githubusercontent.com/9636944/143044337-b127c8f3-832d-4096-9dbb-dd30248ceac2.png)

**Comment by thesmallcreeper** [comment]
Ouch! That's my fault.. looks like gnome 3.32 differs from latest gnomes on that matter.
https://github.com/kgshank/gse-sound-output-device-chooser/blob/2eee4716deeb6b995ec29cc5855879e17c6847f3/sound-output-device-chooser%40kgshank.net/extension.js#L100

@kgshank Have a look and express your opinion on what should be done. Thank you :)

**Comment by izurdo** [comment]
Hi,
Is there a way I could correct this, at least on my rhel 8.5 laptop? Would it be possible that I download the source code and make the correction on the code (if you would tell me, because I am not a developer) so I can compile and make it work? It is quite annoying, I cant use the headset properly.
Thanks!

**Comment by thesmallcreeper** [comment]
@izurdo Can you try PR #209 ? Thank you!

**Comment by kgshank** [comment]
@izurdo The git version is available with fixes. Let me know if this fixes your issues

**Comment by izurdo** [comment]
Hi,
I tried by following the instructions from https://github.com/kgshank/gse-sound-output-device-chooser#installation-instructions but it did not work as expected, I tried it twice even by rebooting the OS, but the error message on "Gnome extensions" is now different, please see attached.
Thanks
![error](https://user-images.githubusercontent.com/9636944/145557071-3b31f5d7-617d-4ace-ada1-9588d200c61d.png)

**Comment by thesmallcreeper** [comment]
@izurdo Can you test #211 ? Thank you!
If not please provide log in order to find the call tree, but it should do the trick.
