### ISSUE TITLE
Allow hiding from all devices

### ISSUE THREAD

**Issue by wvengen** [kgshank/gse-sound-output-device-chooser#22]
I love the feature _Hide selector if there's only one device_. Now my soundcard includes an S/PDIF device that I never use. It looks like there already is support for hiding certain outputs in _Port Settings_. Would it make sense to include _all_ devices in there, so that one can pick the ones that you actually use?

(Then in my case, when a pulseaudio network device is found, the device chooser appears, and when I'm on another network, it disappears - which is exactly what I'm looking for.)

**Comment by kgshank** [comment]
Will add the feature in the next update
