### ISSUE TITLE
[FEATURE] Hide "activated device is hidden" messages

### ISSUE THREAD

**Issue by nelsonblaha** [kgshank/gse-sound-output-device-chooser#223]
I'm sorry if this is already covered somewhere, but I couldn't find it in documentation or existing issues.

I have a lot of sound devices disabled and now I'm a bit pestered by the recurring "Activated device is hidden in Port Settings" warnings. Is there another way?

**Comment by nelsonblaha** [comment]
![image](https://user-images.githubusercontent.com/1343167/153890513-ed72c184-b941-4b40-aa66-ba7384a36ac2.png)

**Comment by enginhu** [comment]
+1

**Comment by nelsonblaha** [comment]
@kgshank perfect!
