### ISSUE TITLE
Only shows "Extension initialising..."

### ISSUE THREAD

**Issue by Squelsh** [kgshank/gse-sound-output-device-chooser#23]
Hi! This looks like a great extension. But it doesn't seem to load completely on my system:
![screenshot from 2017-01-25 19-22-17](https://cloud.githubusercontent.com/assets/898675/22303498/ce6e2210-e333-11e6-9204-36c7965e2c2e.png)

Also the list of ports in the settings is pretty empty:
![screenshot from 2017-01-25 19-24-45](https://cloud.githubusercontent.com/assets/898675/22303528/f3d0f26c-e333-11e6-9646-a877394f7f15.png)

Would be great, if you could give me a hint, how to debug this...

All other shell extensions are disabled.
My desktop system has a **HDA Intel PCH** with an **Realtek ALC887-VD** chip.
Stats:
```
uname -a
Linux gnome-cube 4.4.0-59-generic #80-Ubuntu SMP Fri Jan 6 17:47:47 UTC 2017 x86_64 x86_64 x86_64 GNU/Linux
```

```
lsb_release -a
No LSB modules are available.
Distributor ID:	Ubuntu
Description:	Ubuntu 16.04.1 LTS
Release:	16.04
Codename:	xenial
```

```
gnome-shell --version
GNOME Shell 3.18.5
```

**Comment by Squelsh** [comment]
Now that I installed the **Volume Mixer** extension, your extension does not show up at all ):

**Comment by Squelsh** [comment]
Hmmmm....
After installing Volume Mixer and then disabling it in the extension manager, your extension is up and running. If you want to investigate further, I am happy to deliver logs or stuff. Otherwise you can close this issue.

**Comment by kgshank** [comment]
I haven't used the extension with Volume Mixer for long, can you send the output of the command

`journalctl /usr/bin/gnome-shell`

**Comment by Squelsh** [comment]
Log is empty:
```
journalctl /usr/bin/gnome-shell
-- Logs begin at Mi 2017-01-25 19:33:58 CET, end at Fr 2017-01-27 20:29:59 CET. --
Jan 25 19:34:32 gnome-cube gnome-shell[2152]: GNOME Shell started at Wed Jan 25 2017 19:34:30 GMT+0100 (CET)
```

**Comment by kgshank** [comment]
can you try 
`journalctl -rb | grep "JS LOG:"`

**Comment by Squelsh** [comment]
The output is here:
https://gist.github.com/Squelsh/0507da928638fbbd47dfc4870f095ee3

**Comment by kgshank** [comment]
All the devices are removed immediately after adding, did you by any chance hide all devices in the "Port Settings" in the extension preferences?

**Comment by kgshank** [comment]
Another possibility is the extension is unable to determine the availability properly. Try setting "Show" for all ports under "Port Settings"

**Comment by Squelsh** [comment]
Thanks for your help!
But there is not such thing like "Port Settings" in my GUI. Take a look at the screenshot above...
Or is that the wrong settings GUI?

**Comment by kgshank** [comment]
It seems to be a problem with the extension. I will check the code. As far, "Port Settings" missing, there is a failure in retrieving the list of devices. It usually happens when you use any language other English as display language, I am looking into alternate ways to get the list without any language dependency.

**Comment by Squelsh** [comment]
Cool! Thanks for investigating.
FYI: I switched Gnome-Language to British-English and restarted Gnome. But still the Port Settings stay empty. Or should I have switched to US-English? :)

**Comment by hackel** [comment]
Just wanted to confirm this issue.  I'm running GNOME 3.24.  I do get two HDMI devices under "Port Settings," but changing them from default to show/hide doesn't affect the "Extension initialising..." menu item.  I noticed the following warning in my journal:

Apr 20 11:38:57 hermes gnome-shell[6297]: JS WARNING: [/home/hackel/.local/share/gnome-shell/extensions/sound-output-device-chooser@kgshank.net/base.js 167]: reference to undefined property this._availableDevicesIds[(intermediate value)]

**Comment by supascoopa** [comment]
I had the same problem!!
Before that message started to show I have installed pulseaudio-equalizer and enabled it. I just disabled it and the error stopped.

**Comment by Sioma112233** [comment]
#51 should fix the problem, no when there are no input device it will be be hidden (instead of showing 'Extension initialsing...'

**Comment by kgshank** [comment]
Please verify whether the latest version fixes these issues
