### ISSUE TITLE
"Port Settings" list view is too small

### ISSUE THREAD

**Issue by Cybolic** [kgshank/gse-sound-output-device-chooser#24]
![gnome-shell-screenshot-i8alwy](https://cloud.githubusercontent.com/assets/1196197/23503086/ca90b1be-ff42-11e6-917d-91ac4e1b1ade.png)
This is how it looks in both the latest Ubuntu and Arch.

**Comment by kgshank** [comment]
Will fix it in the next release

**Comment by corebots** [comment]
just installed in fedora 26 with gnome 3.24, still the same 
![screenshot from 2017-07-18 00-46-59](https://user-images.githubusercontent.com/12252430/28293227-7496b7e0-6b53-11e7-980b-9fc62d0d1383.png)

**Comment by mdmower** [comment]
This is my lazy hack until patched by the developer:

1. Open in a text editor: $HOME/.local/share/gnome-shell/extensions/sound-output-device-chooser@kgshank.net/ui/prefs-dialog.gtkbuilder
2. Locate `<object class="GtkScrolledWindow" id="scrolledwindow1">`
3. Add property: `<property name="min-content-height">400</property>`
