### ISSUE TITLE
Extension crashes after screen lock

### ISSUE THREAD

**Issue by mvolf** [kgshank/gse-sound-output-device-chooser#26]
I love this extension but it crashes for me whenever I lock the screen on my laptop. It's impossible to reload it without complete gnome shell restart. If using Wayland gnome shell restart is not available so I need to log out and log in after every screen lock.

**Comment by kgshank** [comment]
I have not tested the extension in Wayland yet. I will check. Mary take a week or more as I am traveling

**Comment by mvolf** [comment]
Hi @kgshank I have the same issue in X server and Wayland. I was just stating that it's even worse in Wayland since Gnome shell doesn't support shell restart under Wayland which means that I can't enable crashed extension without logging out.
But the crash happens both under X server and Wayland.

**Comment by mvolf** [comment]
@kgshank I found this error:
`May 14 10:37:13 hostname gnome-shell[1142]: JS WARNING: [/home/user/.local/share/gnome-shell/extensions/sound-output-device-chooser@kgshank.net/convenience.js 219]: reference to undefined property port.profiles
May 14 10:37:13 hostname gnome-shell[1142]: Extension "sound-output-device-chooser@kgshank.net" had error: TypeError: port.profiles is undefined
`
This error happened at a time the screen got locked/unlocked, so I presume that this is the reason why extension crashed. I hope this helps.

**Comment by mvolf** [comment]
@kgshank When can we expect fix of this bug? Or at least some information? It was added a month ago.
Similar thing was reported in this issue: https://github.com/kgshank/gse-sound-output-device-chooser/issues/27
