### ISSUE TITLE
port.profiles is undefined

### ISSUE THREAD

**Issue by MariusAlch** [kgshank/gse-sound-output-device-chooser#27]
after installing extension i am getting "port.profiles is undefined" when looking at errors using lg tool, is this a known problem?

**Comment by mvolf** [comment]
Does the extension start successfully for you after this error?
I'm getting the same error on unlocking of the screen. It looks like this causes the extension to crash and it can't be reloaded without restarting of the gnome shell.

See my issue for details:
https://github.com/kgshank/gse-sound-output-device-chooser/issues/26

**Comment by MariusAlch** [comment]
I am not able to open extension, I am getting this on install

**Comment by mvolf** [comment]
IT's probably the same issue I'm experiencing then. The only difference is I only experience it on screen unlock.
