### ISSUE TITLE
Show "unplugged" ports too.

### ISSUE THREAD

**Issue by vitorhugods** [kgshank/gse-sound-output-device-chooser#29]
I have a very non-linux compatible soundboard. It took me quite a while to be able to use the internal mic and headphones. Saw many kernel-related posts about the ALC256. After a year, Linux still can't detect when I plug in the headphone.

I can select it manually in PavuControl:
![image](https://user-images.githubusercontent.com/9389043/28313784-808c9872-6b8e-11e7-9d75-fdcfe88671f0.png)

Can't see it when not selected:
![image](https://user-images.githubusercontent.com/9389043/28313813-95a536e2-6b8e-11e7-8b54-4b0a88c1b524.png)

Can see after selected:
![image](https://user-images.githubusercontent.com/9389043/28313831-aaea1ff4-6b8e-11e7-8069-85308597fde3.png)

But can't select it in this extension, it only shows after I select in PavuControl, if I go back to speakers, it no longer is shown there.

I wish I could select "Show Unplugged Ports" in this extension's configuration, so unlucky people like me could hack they way to happiness.

I'm willing to make a pull request, but I've never dealt with Gnome Extensions, and it would be nice to have a little briefing before start. I'm not even sure that the problem is the "Unplugged" status.

**Comment by kgshank** [comment]
Did you try the extension options to show the device always?
