### ISSUE TITLE
Stale output devices shown in outputs list

### ISSUE THREAD

**Issue by abustany** [kgshank/gse-sound-output-device-chooser#30]
Hi,

First of all, thanks for the work you put in the extension :-)

I'm having an issue where "stale" output devices are shown in the outputs list from the extension, whereas GNOME's control center shows the correct list. If it helps, the "stale" devices are dynamically discovered on the network (those are AirPlay devices). I suspect that they were discovered when I was at home, I suspended the laptop, and when I open it again in another place (where the output devices are not available anymore), the list doesn't get refreshed.

Note: this is with version 15 of the extension, but as far as I can see no "core" code was changed between version 15 and 16.

![screenshot-output-chooser](https://user-images.githubusercontent.com/2526296/28514483-667ceb46-705a-11e7-99fc-0e2e63ed116b.png)

**Comment by kgshank** [comment]
Hi Adrien,

This problem is already reported. There were some limitations in the GVC
libraries, that this extension depends on. I am unable to find time to
explore Pulaseaudio for an alternate solution. I will update the extension
soon .

**Comment by kgshank** [comment]
Tracked in #41
