### ISSUE TITLE
Update for Gnome 3.24?

### ISSUE THREAD

**Issue by ogjerstad** [kgshank/gse-sound-output-device-chooser#31]
Would be nice to have support for Gnome 3.24 now that Fedora 26 is out with this version

**Comment by njam** [comment]
The extension seems to work fine for me with Gnome 3.24 so far.
Are you experiencing problems?

**Comment by DidierLoiseau** [comment]
The only issue I think is that the extension is indicated as outdated on https://extensions.gnome.org/extension/906/sound-output-device-chooser/ and it is thus not possible to use it any more without installing it manually (and manually modifying `metadata.json`, I suppose).
