### ISSUE TITLE
Hide selector when only one device error.

### ISSUE THREAD

**Issue by ghost** [kgshank/gse-sound-output-device-chooser#32]
# How to reproduce

0. Must exist an pluggable output sound device (internal sound + hdmi sound output)
1. In extension general settings, enable "Hide selector if there's only one device".
2. Select pluggable output (hdmi)
3. Remove connector
4. Plugin doesn't allow to select internal output.

**Comment by kgshank** [comment]
Closing as the extension has undergone many changes and hoping that the error should be fixed by now
