### ISSUE TITLE
JS warning on Gnome 3.26

### ISSUE THREAD

**Issue by bilelmoussaoui** [kgshank/gse-sound-output-device-chooser#34]
Hey, thanks for the great extension,
Here's a warning i got from journalctl on GNOME 3.25 (the alpha/beta of 3.26)
```
sep 04 04:56:24 lenovo gnome-shell[19623]: JS WARNING: [/home/bilal/.local/share/gnome-shell/extensions/sound-output-device-chooser@kgshank.net/base.js 167]: reference to undefined property this._availableDevicesIds[(intermediate value)]
```

**Comment by cleary** [comment]
Small amount of info and trivial fix here:

https://github.com/micheleg/dash-to-dock/commit/e564630423981777902f308dc093dd512f9be90c
