### ISSUE TITLE
"Port Settings" is empty

### ISSUE THREAD

**Issue by freeroot** [kgshank/gse-sound-output-device-chooser#36]
I have 4 outputs and 2 inputs in the menu. Half of them is related to a stereo speaker connected by usb. Extension works well.

But "Port Settings" in configuration is empty and I would like to use it to hide some outputs.

![impressionecran_1](https://user-images.githubusercontent.com/20989929/33175314-ac4cb8b6-d05b-11e7-8d30-c3ce0255f8b6.png)

**Comment by kgshank** [comment]
Should be fixed in the current release. Please feel free to reopen if issue persists

**Comment by camtauxe** [comment]
This issue is still present for me with Gnome 3.34 on Ubuntu 19.10.
