### ISSUE TITLE
Add option to hide unplugged sound devices

### ISSUE THREAD

**Issue by Naatan** [kgshank/gse-sound-output-device-chooser#40]

**Comment by roumano** [comment]
Yes, will be very good,
otherwise add a option to hide a sound devices ( in a option parametres)

for example, I have 3 sound card, but, i saw 7 sound devices in the pluging as some of my sound devices have a analog/digit output but only use 1 (in pavucontrol, i have less sound devices...)

**Comment by elialbert** [comment]
I believe this has been added
