### ISSUE TITLE
Software sink duplicates in sound output list (bug)

### ISSUE THREAD

**Issue by monte-monte** [kgshank/gse-sound-output-device-chooser#41]
I'm using pulseaudio-dlna to stream audio to upnp sever. It looks for upnp/dlna receivers on the network and makes a pulseaudio sink which records all audio and sends it to remote server. My problem is that after restart of pulseaudio-dlna and/or after waking pc up from suspend the list of sound outputs contains duplicates of network sinks. If you try to switch to one of them it crashes gnome shell. The only way to get rid of them is to restart gnome shell itself, disabling and enabling back this extension doesn't help. I should also mention that those software output duplicates are only present when pulseaudio-dlna is running. This issue affects only this extension, nor system sound settings, nor pavucontrol doesn't show any duplicates.
![screenshot from 2018-04-18 17-10-36](https://user-images.githubusercontent.com/6649967/38951934-bd80115e-4352-11e8-8923-9b0da26c83d0.png)

**Comment by chrisjbillington** [comment]
I experience this too. I have a program that adds a null sink temporarily, and each time I run it a new null sink appears in the extension's list, though `pactl list` does not show them. They've been properly removed from Pulseaudio, but the extension appears to not deal with removal of sinks.

**Comment by terencode** [comment]
Can confirm this as well with jack-sink, trying to click on one of the 5 I had resulted in a crash of gnome-shell.
Here is the backtrace: 
```
nov. 12 16:23:19 terence-arch gnome-shell[1881]: #6   7ffd6ac78ca0 I   self-hosted:979 (7f7dfb4380d0 @ 440)
nov. 12 16:23:19 terence-arch gnome-shell[1881]: #5   55d9f03cc7f0 i   resource:///org/gnome/shell/ui/popupMenu.js:135 (7f7dfb514b80 @ 40)
nov. 12 16:23:19 terence-arch gnome-shell[1881]: #4   55d9f03cc878 i   resource:///org/gnome/shell/ui/popupMenu.js:182 (7f7dfb514e50 @ 25)
nov. 12 16:23:19 terence-arch gnome-shell[1881]: #3   55d9f03cc908 i   resource:///org/gnome/shell/ui/popupMenu.js:499 (7f7dfb51f160 @ 9)
nov. 12 16:23:19 terence-arch gnome-shell[1881]: #2   7ffd6ac76820 I   self-hosted:977 (7f7dfb4380d0 @ 413)
nov. 12 16:23:19 terence-arch gnome-shell[1881]: #1   55d9f03cc988 i   /usr/share/gnome-shell/extensions/sound-output-device-chooser@kgshank.net/base.js:154 (7f7dcee4a5e0 @ 27)
nov. 12 16:23:19 terence-arch gnome-shell[1881]: #0   55d9f03cca10 i   /usr/share/gnome-shell/extensions/sound-output-device-chooser@kgshank.net/extension.js:37 (7f7dcee42700 @ 25)
nov. 12 16:23:19 terence-arch gnome-shell[1881]: == Stack trace for context 0x55d9e0fd6380 ==
nov. 12 16:23:19 terence-arch gnome-shell[1881]: Bail out! Gvc:ERROR:../gnome-shell/subprojects/gvc/gvc-mixer-control.c:545:gvc_mixer_control_change_profile_on_selected_device: assertion failed: (best_profile)
nov. 12 16:23:19 terence-arch gnome-shell[1881]: Gvc:ERROR:../gnome-shell/subprojects/gvc/gvc-mixer-control.c:545:gvc_mixer_control_change_profile_on_selected_device: assertion failed: (best_profile)
nov. 12 16:23:19 terence-arch gnome-shell[1881]: **
nov. 12 16:23:19 terence-arch gnome-shell[1881]: gvc_mixer_card_get_profile: assertion 'GVC_IS_MIXER_CARD (card)' failed
```

**Comment by glaubersm** [comment]
I use my laptop running Arch + Gnome 3.36.6 to stream audio over local netowrk to speakers connected to my desktop computer. Your extension, installed from Gnome Shell extensions website, sometimes shows the same remote output repeatedly. Sound module of Gnome Control Center does not show these repeated outputs.

![sound](https://user-images.githubusercontent.com/15967631/93115907-eff9b900-f692-11ea-8bd6-eeefbbc042cc.png)
