### ISSUE TITLE
Default device changes after restart

### ISSUE THREAD

**Issue by ThatFatPat** [kgshank/gse-sound-output-device-chooser#59]
When a device is chosen, after a restart it's still highlighted in the label but the sound output comes from a different device. To fix it you have to pick a different device and re-pick the first one.

Please let me know if there is any way at all that I can help with solving this issue, logs, code, everything goes.

Thanks in advance,
ThatFatPat

**Comment by kgshank** [comment]
@ThatFatPat  I am not sure whether the issue is still there. If you still have the issues, enable log in extension preferences and send me the `SDC Debug:` messages from command `journalctl -r`

**Comment by eNg1ne85** [comment]
gru 18 10:44:29 nbdgajda gnome-shell[2161]: SDC Debug: Activated: 5
gru 18 10:44:29 nbdgajda gnome-shell[2161]: SDC Debug: Added: 5:Internal Microphone:analog-input-internal-mic
gru 18 10:44:29 nbdgajda gnome-shell[2161]: SDC Debug: Internal Microphone (Built-in Audio)
gru 18 10:44:29 nbdgajda gnome-shell[2161]: SDC Debug: New logic
gru 18 10:44:29 nbdgajda gnome-shell[2161]: SDC Debug: Removed: 4
gru 18 10:44:29 nbdgajda gnome-shell[2161]: SDC Debug: Added: 4:Dock Microphone:analog-input-dock-mic
gru 18 10:44:29 nbdgajda gnome-shell[2161]: SDC Debug: Dock Microphone (Built-in Audio)
gru 18 10:44:29 nbdgajda gnome-shell[2161]: SDC Debug: New logic
gru 18 10:44:29 nbdgajda gnome-shell[2161]: SDC Debug: Removed: 3
gru 18 10:44:29 nbdgajda gnome-shell[2161]: SDC Debug: Added: 3:Microphone:analog-input-mic
gru 18 10:44:29 nbdgajda gnome-shell[2161]: SDC Debug: Microphone (Built-in Audio)
gru 18 10:44:29 nbdgajda gnome-shell[2161]: SDC Debug: New logic
gru 18 10:44:29 nbdgajda gnome-shell[2161]: SDC Debug: Max Id:24
gru 18 10:44:29 nbdgajda gnome-shell[2161]: SDC Debug: Constructorinput
gru 18 10:44:29 nbdgajda gnome-shell[2161]: SDC Debug: SDC: init
gru 18 10:44:29 nbdgajda gnome-shell[2161]: SDC Debug: Removed: 10
gru 18 10:44:29 nbdgajda gnome-shell[2161]: SDC Debug: Added: 10:HDMI / DisplayPort:hdmi-output-0
gru 18 10:44:29 nbdgajda gnome-shell[2161]: SDC Debug: HDMI / DisplayPort (Built-in Audio)
gru 18 10:44:29 nbdgajda gnome-shell[2161]: SDC Debug: New logic
gru 18 10:44:29 nbdgajda gnome-shell[2161]: SDC Debug: Activated: 9
gru 18 10:44:29 nbdgajda gnome-shell[2161]: SDC Debug: Added: 9:HDMI / DisplayPort 2:hdmi-output-1
gru 18 10:44:29 nbdgajda gnome-shell[2161]: SDC Debug: HDMI / DisplayPort 2 (Built-in Audio)
gru 18 10:44:29 nbdgajda gnome-shell[2161]: SDC Debug: New logic
gru 18 10:44:29 nbdgajda gnome-shell[2161]: SDC Debug: Removed: 8
gru 18 10:44:29 nbdgajda gnome-shell[2161]: SDC Debug: Added: 8:HDMI / DisplayPort 3:hdmi-output-2
gru 18 10:44:29 nbdgajda gnome-shell[2161]: SDC Debug: HDMI / DisplayPort 3 (Built-in Audio)
gru 18 10:44:29 nbdgajda gnome-shell[2161]: SDC Debug: New logic
gru 18 10:44:29 nbdgajda gnome-shell[2161]: SDC Debug: Removed: 7
gru 18 10:44:29 nbdgajda gnome-shell[2161]: SDC Debug: Added: 7:HDMI / DisplayPort 4:hdmi-output-3
gru 18 10:44:29 nbdgajda gnome-shell[2161]: SDC Debug: HDMI / DisplayPort 4 (Built-in Audio)
gru 18 10:44:29 nbdgajda gnome-shell[2161]: SDC Debug: New logic
gru 18 10:44:29 nbdgajda gnome-shell[2161]: SDC Debug: Removed: 6
gru 18 10:44:29 nbdgajda gnome-shell[2161]: SDC Debug: Added: 6:HDMI / DisplayPort 5:hdmi-output-4
gru 18 10:44:29 nbdgajda gnome-shell[2161]: SDC Debug: HDMI / DisplayPort 5 (Built-in Audio)
gru 18 10:44:29 nbdgajda gnome-shell[2161]: SDC Debug: New logic
gru 18 10:44:29 nbdgajda gnome-shell[2161]: SDC Debug: Removed: 2
gru 18 10:44:29 nbdgajda gnome-shell[2161]: SDC Debug: Added: 2:Speakers:analog-output-speaker
gru 18 10:44:29 nbdgajda gnome-shell[2161]: SDC Debug: Speakers (Built-in Audio)
gru 18 10:44:29 nbdgajda org.gnome.Nautilus[2107]: Failed to register: Unable to acquire bus name 'org.gnome.Nautilus'
gru 18 10:44:29 nbdgajda gnome-shell[2161]: SDC Debug: New logic
gru 18 10:44:29 nbdgajda gnome-shell[2161]: SDC Debug: Added: 1:Headphones:analog-output-headphones
gru 18 10:44:29 nbdgajda gnome-shell[2161]: SDC Debug: Headphones (Built-in Audio)
gru 18 10:44:28 nbdgajda gnome-shell[2161]: SDC Debug: New logic
gru 18 10:44:28 nbdgajda gnome-shell[2161]: SDC Debug: Max Id:23
gru 18 10:44:28 nbdgajda gnome-shell[2161]: SDC Debug: Constructoroutput
gru 18 10:44:28 nbdgajda gnome-shell[2161]: SDC Debug: SDC: init

**Comment by maqp** [comment]
I'm having the same issue -- it also happens when the computer is put to suspend.

**Comment by beastybeast** [comment]
I have the same problem ;-)

**Comment by jspaetzel** [comment]
I just had it happen to me and the controls in gnome-control-center are wrong also so I think this is probably an issue outside this extension.

**Comment by maqp** [comment]
@jspaetzel I agree. After switching to Fedora 32 the issues have completely disappeared.
