### ISSUE TITLE
Not compatible with Gnome 3.33

### ISSUE THREAD

**Issue by BjoernDaase** [kgshank/gse-sound-output-device-chooser#63]
I tried out Gnome 3.33 on Fedora Rawhide today, but sadly this extension is yet not compatible. The following stacktrace can be found in the gnome-shell journal:

`Extension "sound-output-device-chooser@kgshank.net" had error: TypeError: this._setLog is not a function`

**Comment by kgshank** [comment]
Extension updated for 3.34 New version should be available in extensions.gnome.org after approval. As always the latest source is available in github

**Comment by parndt** [comment]
thank you @kgshank 	! :heart:

**Comment by bellini666** [comment]
Is the new update already available in eog? I just updated to 3.34 and it is giving me that exact error.

**Comment by kgshank** [comment]
Yes, the latest version is already available in eog. Restarting shell might help. Please check
