### ISSUE TITLE
Deal with long sink/source names

### ISSUE THREAD

**Issue by terencode** [kgshank/gse-sound-output-device-chooser#65]
When the sinks or sources have a long name, the menu just tries to fit the whole text and it results on very large menu: 
![gse-input-ouput-switcher](https://user-images.githubusercontent.com/12665563/65261852-6825b100-db09-11e9-8e0c-3a8699fbf044.png)

Three solutions I can think of: 
- Set a max character limit and replace anything after with '...'
- Allow to rename the sinks/sources from the extension settings, but maybe it's better to do it from pulseaudio config files.
- Keep the default menu size but make somehow the text slide from right to left.

**Comment by kgshank** [comment]
Added a new option to disable the behavior completely for now. I will see the feasibility of your suggestions. If possible test the current version from git

**Comment by terencode** [comment]
Thanks, your current solution works and is at leas good enough for me.
Feel free to close if you do not improve it any further.

**Comment by terencode** [comment]
Well uh actually I experience a weird behaviour where I get duplicate entries for both input and output


![output](https://user-images.githubusercontent.com/12665563/65343474-60cbd980-dbd5-11e9-9a6e-53c9b13bb282.gif)

**Comment by kgshank** [comment]
This is a old behaviour, sometimes the extension is not signaled for removed devices. I am exploring options to avoid this

**Comment by kgshank** [comment]
#41 is the same as the second issue.

**Comment by terencode** [comment]
Can't reproduce anymore.
