### ISSUE TITLE
version 24 does not start

### ISSUE THREAD

**Issue by Strykar** [kgshank/gse-sound-output-device-chooser#67]
This extension was working fine until the update to v `24` on Arch linux/Gnome `3.34.0`.
Installed from extensions.gnome.org; I've enabled logs but don't see any, how do I troubleshoot this?

> $ python -V
> Python 3.7.4
> $ uname -r
> 5.3.0-arch1-1-ARCH

**Comment by kgshank** [comment]
`journalct -r` should have the log messages. Please share the messages.

**Comment by abienz** [comment]
This is the error I get.

`JS ERROR: Extension sound-output-device-chooser@kgshank.net: TypeError: this._setLog is not a function
                                            SoundDeviceChooserBase@/~/.local/share/gnome-shell/extensions/sound-output-device-chooser@kgshank.net/base.js:42:9
                                            SoundOutputDeviceChooser@/~/.local/share/gnome-shell/extensions/sound-output-device-chooser@kgshank.net/extension.js:30:9
                                            enable@/~/.local/share/gnome-shell/extensions/sound-output-device-chooser@kgshank.net/extension.js:109:27
                                            _callExtensionEnable@resource:///org/gnome/shell/ui/extensionSystem.js:131:13
                                            loadExtension@resource:///org/gnome/shell/ui/extensionSystem.js:263:21
                                            _loadExtensions/<@resource:///org/gnome/shell/ui/extensionSystem.js:473:13
                                            collectFromDatadirs@resource:///org/gnome/shell/misc/fileUtils.js:27:17
                                            _loadExtensions@resource:///org/gnome/shell/ui/extensionSystem.js:452:9
                                            _enableAllExtensions@resource:///org/gnome/shell/ui/extensionSystem.js:482:13
                                            _sessionUpdated@resource:///org/gnome/shell/ui/extensionSystem.js:513:13
                                            init@resource:///org/gnome/shell/ui/extensionSystem.js:31:9
                                            _initializeUI@resource:///org/gnome/shell/ui/main.js:238:5
                                            start@resource:///org/gnome/shell/ui/main.js:138:5
                                            @<main>:1:31`

**Comment by kgshank** [comment]
@abienz  This error is already fixed for 3.34 update. Can you update the extension from extensions.gnome.org and try again. Whats the version of your gnome-shell?

**Comment by abienz** [comment]
Ah I see.

My gnome-shell version is 3.34.0, and I'm using the 'shell version' of the extension from extensions.gnome.org.

I've tried uninstalling and reinstalling the extension and it doesn't load.

I know there is a problem with it as the extension website shows an 'error' tag by the install and configure icons

**Comment by abienz** [comment]
I found on Arch there was a new update to gnome-shell, this latest version has the extension working properly.

Thanks

**Comment by Strykar** [comment]
Confirming @abienz has the right solution, apparently it was an issue with Arch's gnome-shell.
