### ISSUE TITLE
Input-output list gets duplicated after screen lock gnome-3.34

### ISSUE THREAD

**Issue by Kallestofeles** [kgshank/gse-sound-output-device-chooser#68]
Whlist using the new gnome 3.34, input-output devices' list gets an extra entry every time computer's screen is locked:
![image](https://user-images.githubusercontent.com/3207177/65423484-ca382c00-de11-11e9-931e-533e0389372d.png)
Please let me know what logs are needed if any for fix. Thank you!

OS: Arch Linux
DE: Gnome v3.34

**Comment by terencode** [comment]
Probably a duplicate of #41.

**Comment by kgshank** [comment]
duplicate of #66

**Comment by kgshank** [comment]
Please retest with the git version

**Comment by Kallestofeles** [comment]
Thanks, based on a quick test, this seems to have fixed it.
