### ISSUE TITLE
Changing device from shortcut menu doesn't show device is changed.

### ISSUE THREAD

**Issue by abienz** [kgshank/gse-sound-output-device-chooser#69]
When I try and switch devices from my speaker to my headphones I use the menu in the status bar area.

Upon clicking my headphone device the menu closes and my headphones are now functional (I use USB headphones).

However the bug I am seeing is that when I check the menu to see what device is selected, it still shows my speakers (Line Out (Built-in audio)).

The only thing I see in my journalctl -r is the following:

`Sep 24 20:31:47 arch-desk gnome-shell[831]: #1   7fffc5e1e670 b   self-hosted:975 (7f201b52c1f0 @ 392)
Sep 24 20:31:47 arch-desk gnome-shell[831]: #0   557a2d3c93a0 i   resource:///org/gnome/shell/ui/workspace.js:695 (7f202006c1f0 @ 15)
Sep 24 20:31:47 arch-desk gnome-shell[831]: == Stack trace for context 0x557a2134f320 ==
Sep 24 20:31:47 arch-desk gnome-shell[831]: Object St.Button (0x557a2c787fc0), has been already deallocated — impossible to get any property from it. This might be caused by the object having been destroyed from C code using something such as destroy(),`

**Comment by kgshank** [comment]
Did you try the version from git or installed from extensions.gnome.org  

The git version has some fixes that was available in extensions.gnome.org .

**Comment by abienz** [comment]
I'm using the version from extensions.gnome.org.

**Comment by kgshank** [comment]
Please try updating now from extensions.gnome.org.. The new version was approved just 2 hrs back.

**Comment by abienz** [comment]
I just got a notification that there was an update, thanks :)

I had to restart my machine for the changes to show, but so far it seems to switch device and update the selected device in the status bar area correctly.

**Comment by michaelarnauts** [comment]
It indeed is fixed with the release from a few hours ago. Restarting gnome shell was enough: alt+F2, and `r` did the trick.

**Comment by kgshank** [comment]
Thanks for confirmation
