### ISSUE TITLE
The switcher disappears after unlocking the screen

### ISSUE THREAD

**Issue by anassahmed** [kgshank/gse-sound-output-device-chooser#7]
I notice that the switcher is working well after the first login and after restarting the shell (Alt + F2 then 'r') but when I lock the screen, then unlock it again, I see the switcher disappears from the gnome shell menu.

I've stumbled upon the following lines from the Journal:
```
Feb 11 02:18:17 anass-galago gnome-shell.desktop[2505]: Gjs-Message: JS LOG: Max Id:11
Feb 11 02:18:17 anass-galago gnome-shell.desktop[2505]: Gjs-Message: JS LOG: Profiles not defined
Feb 11 02:18:17 anass-galago gnome-shell.desktop[2505]: Gjs-Message: JS LOG: analog-output-speaker found
Feb 11 02:18:17 anass-galago gnome-shell.desktop[2505]: Gjs-Message: JS LOG: Port Found!!!
Feb 11 02:18:17 anass-galago gnome-shell.desktop[2505]: Gjs-Message: JS LOG: Added: 5
Feb 11 02:18:17 anass-galago gnome-shell.desktop[2505]: Gjs-Message: JS LOG: Profiles not defined
Feb 11 02:18:17 anass-galago gnome-shell.desktop[2505]: Gjs-Message: JS LOG: headset-output not found
Feb 11 02:18:17 anass-galago gnome-shell.desktop[2505]: Gjs-Message: JS LOG: card_index=0
Feb 11 02:18:17 anass-galago gnome-shell.desktop[2505]: Gjs-Message: JS LOG: card_index=1
Feb 11 02:18:17 anass-galago gnome-shell.desktop[2505]: Gjs-Message: JS LOG: card_index=4
Feb 11 02:18:17 anass-galago gnome-shell.desktop[2505]: (gnome-shell:2505): Gjs-WARNING **: JS ERROR: TypeError: cards[cardIndex] is undefined
Feb 11 02:18:17 anass-galago gnome-shell.desktop[2505]: parseOutput@/home/anass/.local/share/gnome-shell/extensions/sound-output-device-chooser@kgshank.net/convenience.js:150
Feb 11 02:18:17 anass-galago gnome-shell.desktop[2505]: refreshCards@/home/anass/.local/share/gnome-shell/extensions/sound-output-device-chooser@kgshank.net/convenience.js:100
Feb 11 02:18:17 anass-galago gnome-shell.desktop[2505]: getProfiles@/home/anass/.local/share/gnome-shell/extensions/sound-output-device-chooser@kgshank.net/convenience.js:67
Feb 11 02:18:17 anass-galago gnome-shell.desktop[2505]: SoundOutputDeviceChooser<._outputAdded@/home/anass/.local/share/gnome-shell/extensions/sound-output-device-chooser@kgshank.net/extension.js:139
Feb 11 02:18:17 anass-galago gnome-shell.desktop[2505]: wrapper@resource:///org/gnome/gjs/modules/lang.js:169
Feb 11 02:18:17 anass-galago gnome-shell.desktop[2505]: SoundOutputDeviceChooser<._lateInit@/home/anass/.local/share/gnome-shell/extensions/sound-output-device-chooser@kgshank.net/extension.js:85
Feb 11 02:18:17 anass-galago gnome-shell.desktop[2505]: wrapper@resource:///org/gnome/gjs/modules/lang.js:169
Feb 11 02:18:18 anass-galago gnome-shell.desktop[2505]: Gjs-Message: JS LOG: profile changed: a2dp_sink
```

**Comment by kgshank** [comment]
Please post the output of the command when the switcher disappears

`pactl list cards`

**Comment by anassahmed** [comment]
I've attached the output of `pactl` before disappearance and after disappearance. I don't notice a difference, but maybe at the time of unlocking the screen, the plugin can't catch the output correctly. I really don't know.

[pactl.after.txt](https://github.com/kgshank/gse-sound-output-device-chooser/files/135485/pactl.after.txt)
[pactl.before.txt](https://github.com/kgshank/gse-sound-output-device-chooser/files/135486/pactl.before.txt)

**Comment by kgshank** [comment]
I have made some changes to the code, will be pushing it soon to extensions site after some testing. Meanwhile do you see Bluetooth headset in the output section of gnome control center -> sound settings. If possible send me a screenshot of the same.

**Comment by anassahmed** [comment]
Attached is before locking the screen and after locking the screen and losing the switcher, I reopened the GNOME control center again to make sure it doesn't persist settings between lock-screens.

![screenshot from 2016-02-20 01-46-28 (Before)](https://cloud.githubusercontent.com/assets/928614/13192387/fb89e940-d773-11e5-9437-ff2b8a089b30.png)
![screenshot from 2016-02-20 01-47-00 (After)](https://cloud.githubusercontent.com/assets/928614/13192386/fb850182-d773-11e5-8172-640975e60894.png)

**Comment by kgshank** [comment]
New version uploaded to extensions website. Wait for approval and let me know if your problem is solved

**Comment by anassahmed** [comment]
Yeah, Finally!

It had been fixed. It was an annoying bug which forced me to restart the gnome-shell every time I lock the screen.

Thank you very much.
