### ISSUE TITLE
Add an option to switch all inputs/outputs when switching input/output

### ISSUE THREAD

**Issue by terencode** [kgshank/gse-sound-output-device-chooser#72]
My use case is not to have to change every program output when I switch between my headphones and my speakers.

**Comment by kgshank** [comment]
Do you mean to switch the device only for the current active application or pre-selected list?

**Comment by terencode** [comment]
All active applications would switch to the selected output/input.

**Comment by goncalossilva** [comment]
I would love this, too. Connecting and disconnecting devices is maddening. :disappointed:

**Comment by kgshank** [comment]
Same as #88 

Program specific option, or change devices that use the default sink

**Comment by terencode** [comment]
Makes sense.
