### ISSUE TITLE
Extension crashing on specific option selection on Gnome 3.34.1

### ISSUE THREAD

**Issue by Cyvain87** [kgshank/gse-sound-output-device-chooser#74]
I’m not sure what exact info you need from the system but recently when using the extension on Manjaro gnome I am having to use an external dac to use my headphones when only a day or so ago I could plug them in directly and it would work. The extension seems to completely crash everything when selecting the headphones without the dac but I can select the dac fine. I have not done any updates since it was last working so I’m sure it’s not an update doing it unless it’s a compatibility issue with gnome 3.34.1.  I would appreciate assistance with working this out please. If there is extra info you need just let me know and I’ll get hold of it.

**Comment by kgshank** [comment]
Can you enable log messages in the extension preferences and share the journalctl out

**Comment by padys** [comment]
On my Fedora 31 with Gnome 3.34.1 this extension crashes. In `journalctl` I could find entries like that:
```
lis 01 08:05:31 hp-z230 gnome-software[2166]: sound-output-device-chooser_kgshank.net has error: TypeError: this._setLog is not a function
lis 01 08:05:44 hp-z230 python[11028]: detected unhandled Python exception in '/home/padys/.local/share/gnome-shell/extensions/sound-output-device-chooser@kgshank.net/utils/pa_helper.py'
lis 01 08:05:44 hp-z230 abrt-server[11029]: Executable '/home/padys/.local/share/gnome-shell/extensions/sound-output-device-chooser@kgshank.net/utils/pa_helper.py' doesn't belong to any package and ProcessUnpackaged is set to 'no'
lis 01 08:05:44 hp-z230 abrt-server[11029]: 'post-create' on '/var/spool/abrt/Python3-2019-11-01-08:05:44-11028' exited with 1
lis 01 08:05:44 hp-z230 abrt-server[11029]: Deleting problem directory '/var/spool/abrt/Python3-2019-11-01-08:05:44-11028'
```

**Comment by kgshank** [comment]
The new updates should have fixed the issues, please feel free to reopen if the issue is still there.
