### ISSUE TITLE
Remove inactive network outputs from list

### ISSUE THREAD

**Issue by tomashavlas** [kgshank/gse-sound-output-device-chooser#8]
I've been experimenting with pulseaudio over network and I've discovered that if I disconnect from network, or the remote pulseaudio server dies, the inacive output stay is not removed from list, and if I try to choose it whole gnome shell crashs. To remove inactive output from list I have to log out.
The inactive output gets removed from gnome control center sound settings, so it's just problem with this extension, it would be nice to have this fixed.

**Comment by kgshank** [comment]
Please post the gnome shell console messages when the issue happens.

**Comment by tomashavlas** [comment]
So I was able to figure out following:

1. As soon as network card is discovered following line starts to repeat in log:
`(gnome-shell:4225): Gvc-WARNING **: Device did not have an appropriate card`

2. When pulseaudio network card "dies" it is detected but it is not removed from list because:
`Gjs-Message: JS LOG: Device removed, but not hiding as its set to be shown always`

I'm attaching complete log [gnome-shell.log.txt](https://github.com/kgshank/gse-sound-output-device-chooser/files/185057/gnome-shell.log.txt)

**Comment by kgshank** [comment]
Is the option to show the port always turned on in the extension preferences under port settings?

**Comment by tomashavlas** [comment]
The network card doesn't even show at the extensions preferences, however all of present cards are set to default and there is nothing relevant in log when I open extension preferences.

**Comment by kgshank** [comment]
I have identified the issue, I will post an update soon.

**Comment by kgshank** [comment]
There is a new update in extensions.gnome.org. Can you confirm whether the issue is resolved?

**Comment by tomashavlas** [comment]
I've made a few quick tests and it seems to be working correctly.

**Comment by kgshank** [comment]
Thanks for confirming. Please let me know if you encounter any other issues
