### ISSUE TITLE
Extension initialising...with USB DAC

### ISSUE THREAD

**Issue by toto6038** [kgshank/gse-sound-output-device-chooser#80]
![Screenshot from 2019-11-24 22-15-25](https://user-images.githubusercontent.com/50100922/69496066-dff8c900-0f08-11ea-8e80-a9e9fbc2b603.png)

Hello, I've experienced this problem when connecting to a Nextdrive Spectra X. With the resolution in #23 , disabling the "Show input devices" within "Input Devices" do help mitigate the problem. Last but not least, I want to appreciate the author's effort for making this helpful extension.

Gnome shell version: 3.28.4
OS: Ubuntu 18.04.3 LTS
Linux kernel version: 5.3.0-22-generic
CPU: Intel Xeon E3-1230V3
GPU: Nvidia Geforce GTX 760

**Comment by raulcraveiro** [comment]
I have the same "Extension Initializing" problem when I connect my bluetooth headphone. 🤔

**Comment by kgshank** [comment]
@raulcraveiro Did you try the workaround to disable the input devices. If you are using an older shell version, its difficult for me to test it.  Let me know the gnome shell version and the extension version

**Comment by raulcraveiro** [comment]
@kgshank Now I'm on Ubuntu 19.10 and It's working normally ;)

**Comment by kgshank** [comment]
Thanks for confirming
