### ISSUE TITLE
names of sources swapped by extension

### ISSUE THREAD

**Issue by Saroumane** [kgshank/gse-sound-output-device-chooser#88]
See pictures. (Pavucontrol on the left shows where the sound is really ouput)

![Screenshot from 2020-02-19 12-26-48](https://user-images.githubusercontent.com/22261137/74830455-76c00080-5313-11ea-99fc-176fa75d56e7.png)
![Screenshot from 2020-02-19 12-27-22](https://user-images.githubusercontent.com/22261137/74830461-79225a80-5313-11ea-8b35-63b3df82b0bb.png)

Version tested : latest available as of 19/02/2020 on https://extensions.gnome.org/extension/906/sound-output-device-chooser/
Ubuntu 19.10

**Comment by kgshank** [comment]
Can you elaborate more. Whats the default output device as show in the sound settings?

**Comment by Saroumane** [comment]
Good question ! It appears that `gse-sound-output-device-chooser` stays consistent with Ubuntu settings.
In fact I tried to reproduce the "bug" : whatever I do with `pavucontrol` (i.e. whatever output devices I choose for programs in "Playback" tab), Ubuntu "Output device" in Sound Settings stays the same. And so does this extension.

But : it's totally different if you use this extension (or Ubuntu Sound settings) : `pavucontrol` is immediately updated with new Output device settings, applied to all programs.

Conclusion : this extension is consistent with Ubuntu sound settings, but neither can be used to control multiples programs sound ouput, nor in combination with `pavucontrol`

**Comment by kgshank** [comment]
Yes, that's exactly the intention of the extension. It was to be a shortcut for the default system sound device. I think there was a similar defect, let me see if I can take it up as an enhancement.

**Comment by Saroumane** [comment]
It sounds tricky to control different programs output in the cramped space of the menu extension...  But if you can do it, well done !
