### ISSUE TITLE
[regression] Immediately removed after installation

### ISSUE THREAD

**Issue by MattSturgeon** [kgshank/gse-sound-output-device-chooser#9]
This extension fails to install correctly; I toggle the switch to "on" and confirm "Install", it briefly shows as "on" for a split second before switching itself off again.

The menu does not appear after attempting instillation, the extension does not show up in GNOME Tweak Tool or on [the website](https://extensions.gnome.org/local/)

The extension installed and worked fine previously, however an upgrade (to something) caused this regression.

I can reproduce this on both my Arch machine and my Fedora machine.

**Comment by kgshank** [comment]
I tried installing from the website and it installs normally. Do you have any other extension related to Volume controls installed? Post the console messages during installation, it will be useful for debugging.

**Comment by MattSturgeon** [comment]
Oddly it seems to be working normally now... Perhaps I am going crazy!

Which console? I've never seen any output in the JS console, and I doubt chrome would print anything relevant to `stderr`
