### ISSUE TITLE
Not ready for 3.36

### ISSUE THREAD

**Issue by BjoernDaase** [kgshank/gse-sound-output-device-chooser#90]
Since gnome-shell 3.35.92 (3.35.91 worked fine) the extension does not activate anymore. The following is printed into the journal:
```
Mär 03 22:50:14 xps-9370 gnome-shell[4368]: JS ERROR: Extension sound-output-device-chooser@kgshank.net: TypeError: theme is null
                                             init@/home/bjoern/.local/share/gnome-shell/extensions/sound-output-device-chooser@kgshank.net/extension.js:168:5
                                             _callExtensionInit@resource:///org/gnome/shell/ui/extensionSystem.js:382:50
                                             loadExtension@resource:///org/gnome/shell/ui/extensionSystem.js:308:27
                                             _loadExtensions/<@resource:///org/gnome/shell/ui/extensionSystem.js:536:18
                                             collectFromDatadirs@resource:///org/gnome/shell/misc/fileUtils.js:27:17
                                             _loadExtensions@resource:///org/gnome/shell/ui/extensionSystem.js:515:19
                                             _enableAllExtensions@resource:///org/gnome/shell/ui/extensionSystem.js:545:18
                                             _sessionUpdated@resource:///org/gnome/shell/ui/extensionSystem.js:576:18
                                             init@resource:///org/gnome/shell/ui/extensionSystem.js:54:14
                                             _initializeUI@resource:///org/gnome/shell/ui/main.js:244:22
                                             start@resource:///org/gnome/shell/ui/main.js:138:5
                                             @<main>:1:47
```

**Comment by kleinph** [comment]
It worked for me on Gnome 3.36 with X, but not with Wayland

**Comment by Scotty-Trees** [comment]
GNOME 3.36 is going to be released March 11 and I like your extension very much and hope it can be updated to include support for GNOME 3.36. Keep up the great work!

**Comment by kgshank** [comment]
v 26 released with updates for 3.36

**Comment by terencode** [comment]
I still see this with your new update:
```
JS ERROR: Extension sound-output-device-chooser@kgshank.net: ReferenceError: extensionMeta is not defined
                                                    enable@/usr/share/gnome-shell/extensions/sound-output-device-chooser@kgshank.net/extension.js:110:13
                                                    _callExtensionEnable@resource:///org/gnome/shell/ui/extensionSystem.js:160:32
                                                    loadExtension@resource:///org/gnome/shell/ui/extensionSystem.js:311:26
                                                    _loadExtensions/<@resource:///org/gnome/shell/ui/extensionSystem.js:536:18
                                                    collectFromDatadirs@resource:///org/gnome/shell/misc/fileUtils.js:27:17
                                                    _loadExtensions@resource:///org/gnome/shell/ui/extensionSystem.js:515:19
                                                    _enableAllExtensions@resource:///org/gnome/shell/ui/extensionSystem.js:545:18
                                                    _sessionUpdated@resource:///org/gnome/shell/ui/extensionSystem.js:576:18
                                                    init@resource:///org/gnome/shell/ui/extensionSystem.js:54:14
                                                    _initializeUI@resource:///org/gnome/shell/ui/main.js:244:22
                                                    start@resource:///org/gnome/shell/ui/main.js:138:5
                                                    @<main>:1:47
```

**Comment by nunocastromartins** [comment]
Works fine for me! The only (minor) issue I found is that the extension's name renders like this in the new GNOME Extensions app:
![image](https://user-images.githubusercontent.com/8314616/76435712-436f0f80-63af-11ea-91f0-beb94fba1e1d.png)

Thank you for your work! :)

**Comment by xMordax** [comment]
Got the same error as @terencode

**Comment by kgshank** [comment]
Last update inactivated in extensions.gnome.org.
New update uploaded, waiting for review

**Comment by terencode** [comment]
it's still broken with your latest changes but somehow works when using v25 (5c3c601eb4cc96fd4dff2b44dd7a76b427504757)

**Comment by kgshank** [comment]
@terencode can you share the messages from journalctl

**Comment by terencode** [comment]
@kgshank it's the same as my previous message I'll double check I correctly updated though.

**Comment by kgshank** [comment]
@terencode  can you test the update from git

**Comment by terencode** [comment]
Working :+1:

**Comment by kgshank** [comment]
@terencode thanks for confirming

**Comment by xMordax** [comment]
Still does not work for me GNOME Shell 3.36.0.
```
Archive:  /tmp/MH5DH0.shell-extension.zip
  inflating: ~/.local/share/gnome-shell/extensions/sound-output-device-chooser@kgshank.net/base.js
  inflating: ~/.local/share/gnome-shell/extensions/sound-output-device-chooser@kgshank.net/convenience.js
  inflating: ~/.local/share/gnome-shell/extensions/sound-output-device-chooser@kgshank.net/utils/pa_helper.py
   creating: ~/.local/share/gnome-shell/extensions/sound-output-device-chooser@kgshank.net/ui/
  inflating: ~/.local/share/gnome-shell/extensions/sound-output-device-chooser@kgshank.net/license
  inflating: ~/.local/share/gnome-shell/extensions/sound-output-device-chooser@kgshank.net/schemas/gschemas.compiled
  inflating: ~/.local/share/gnome-shell/extensions/sound-output-device-chooser@kgshank.net/extension.js
  inflating: ~/.local/share/gnome-shell/extensions/sound-output-device-chooser@kgshank.net/schemas/org.gnome.shell.extensions.sound-output-device-chooser.gschema.xml
  inflating: ~/.local/share/gnome-shell/extensions/sound-output-device-chooser@kgshank.net/icons/blank.png
  inflating: ~/.local/share/gnome-shell/extensions/sound-output-device-chooser@kgshank.net/ui/prefs-dialog.gtkbuilder
  inflating: ~/.local/share/gnome-shell/extensions/sound-output-device-chooser@kgshank.net/prefs.js
  inflating: ~/.local/share/gnome-shell/extensions/sound-output-device-chooser@kgshank.net/utils/libpulse_introspect.py
 extracting: ~/.local/share/gnome-shell/extensions/sound-output-device-chooser@kgshank.net/metadata.json
JS ERROR: Extension sound-output-device-chooser@kgshank.net: ReferenceError: extensionMeta is not defined
enable@~/.local/share/gnome-shell/extensions/sound-output-device-chooser@kgshank.net/extension.js:110:13
_callExtensionEnable@resource:///org/gnome/shell/ui/extensionSystem.js:160:32
loadExtension@resource:///org/gnome/shell/ui/extensionSystem.js:311:26
callback@resource:///org/gnome/shell/ui/extensionDownloader.js:204:39
gotExtensionZipFile/<@resource:///org/gnome/shell/ui/extensionDownloader.js:97:13
```

**Comment by jaspervanbrian** [comment]
Installed via https://extensions.gnome.org/
It shows `ERROR`

I'm on Pop_OS! 19.10
![image](https://user-images.githubusercontent.com/24638813/76545965-a2bf4380-64c5-11ea-9502-c33feb052666.png)

**Comment by Galzzly** [comment]
I, too, have found that this is erroring for me too. I installed via https://extensions.gnome.org/

I do note, though, that Gnome 3.36 is not an option on the drop down.

Following errors are seen in journalctl
```
JS ERROR: Extension sound-output-device-chooser@kgshank.net: TypeError: theme is null
init@/home/liamg/.local/share/gnome-shell/extensions/sound-output-device-chooser@kgshank.net/extension.js:168:5
_callExtensionInit@resource:///org/gnome/shell/ui/extensionSystem.js:382:50
loadExtension@resource:///org/gnome/shell/ui/extensionSystem.js:308:27
_loadExtensions/<@resource:///org/gnome/shell/ui/extensionSystem.js:536:18
collectFromDatadirs@resource:///org/gnome/shell/misc/fileUtils.js:27:17
_loadExtensions@resource:///org/gnome/shell/ui/extensionSystem.js:515:19
_enableAllExtensions@resource:///org/gnome/shell/ui/extensionSystem.js:545:18
_sessionUpdated@resource:///org/gnome/shell/ui/extensionSystem.js:576:18
init@resource:///org/gnome/shell/ui/extensionSystem.js:54:14
_initializeUI@resource:///org/gnome/shell/ui/main.js:244:22
start@resource:///org/gnome/shell/ui/main.js:138:5
@<main>:1:47
```

I've found that removing and reinstalling makes the extension work for the session until my laptop is restarted.

**Comment by mrpeabody** [comment]
v28 is still broken on Arch and Gnome 3.36

**Comment by RemiCardona** [comment]
gnome-shell 3.34 here (on Gentoo FWIW)

After much fiddling around, deleting the extension directory from `~/.local/share/gnome-shell/extensions`, reinstalling it (from extensions.gnome.org) *AND* restarting gnome-shell (alt-F2 → `r`) seems to work. No errors in the journal and the menu items are back.

**Comment by puresick** [comment]
v28 on Gnome 3.36 and latest Arch Linux works! (installed via Software App)

**Comment by spawnedc** [comment]
v28 on Gnome 3.34.4 and latest Manjaro works! (installed via AUR)

**Comment by hswong3i** [comment]
v28 working with Ubuntu 19.10 + X11 + vanilla-gnome-desktop, by:
- Uninstall addon from https://extensions.gnome.org/extension/906/sound-output-device-chooser/
- `Alt + F2` -> `r` -> Enter
- Reinstall addon from https://extensions.gnome.org/extension/906/sound-output-device-chooser/

**Comment by brozs** [comment]
> I still see this with your new update:
> 
> ```
> JS ERROR: Extension sound-output-device-chooser@kgshank.net: ReferenceError: extensionMeta is not defined
>                                                     enable@/usr/share/gnome-shell/extensions/sound-output-device-chooser@kgshank.net/extension.js:110:13
>                                                     _callExtensionEnable@resource:///org/gnome/shell/ui/extensionSystem.js:160:32
>                                                     loadExtension@resource:///org/gnome/shell/ui/extensionSystem.js:311:26
>                                                     _loadExtensions/<@resource:///org/gnome/shell/ui/extensionSystem.js:536:18
>                                                     collectFromDatadirs@resource:///org/gnome/shell/misc/fileUtils.js:27:17
>                                                     _loadExtensions@resource:///org/gnome/shell/ui/extensionSystem.js:515:19
>                                                     _enableAllExtensions@resource:///org/gnome/shell/ui/extensionSystem.js:545:18
>                                                     _sessionUpdated@resource:///org/gnome/shell/ui/extensionSystem.js:576:18
>                                                     init@resource:///org/gnome/shell/ui/extensionSystem.js:54:14
>                                                     _initializeUI@resource:///org/gnome/shell/ui/main.js:244:22
>                                                     start@resource:///org/gnome/shell/ui/main.js:138:5
>                                                     @<main>:1:47
> ```

I was able to fix this by changing my `~/.local/share/gnome-shell/extensions/sound-output-device-chooser@kgshank.net/extension.js:174`

```
function init() {
    return new SDCInstance();
}
```
to
```
function init(extensionMeta) {
    return new SDCInstance();
}
```

**Comment by kgshank** [comment]
@brozs  Try uninstalling and reinstalling from extensions.gnome.org The messages you have reported doesn't correspond to the latest source

**Comment by brozs** [comment]
I'm sure I did that before changing "extension.js". It failed for me everytime until I made the change.

**Comment by wbolster** [comment]
seems this works now, and this issue can be closed? thanks, @kgshank!

**Comment by brozs** [comment]
Works for me.
