### ISSUE TITLE
"image-missing" icon on menu with gnome-shell 3.36.1

### ISSUE THREAD

**Issue by terencode** [kgshank/gse-sound-output-device-chooser#95]
With 3.36.1, gnome-shell now show an "image-missing" icon when it cannot find a given one.

From https://github.com/kgshank/gse-sound-output-device-chooser/commit/d1825733c82791972277d5f1a11d452d1e9ff0dc, the extension tries to load a 'blank' icon, which is probably a workaround to get the spacing in the menu right without the need to show an icon there.

The result is the following:
![image](https://user-images.githubusercontent.com/12665563/78088197-b6bedc80-73c3-11ea-8e43-431b905604c8.png)

**Comment by mattia-b89** [comment]
not fixed
(updated to latest commint 6d07da2a1c3757cb9242fa061415ae4b6ef9122b)

**Comment by terencode** [comment]
It will be when gnome-shell 3.36.2 is released.

**Comment by mattia-b89** [comment]
just to report: still here with 3.36.2

**Comment by terencode** [comment]
@mattia-b89 That's weird, are you sure the latest version is not being overwritten by a left over in `~/.local/share/gnome-shell-extension` ? Anything in the log?

**Comment by mattia-b89** [comment]
No, because I install it system-wide (in `/usr/share/gnome-shell/extensions`);  
No errors in log (`journactl`).

If I can help in order way, I am here!

**Comment by terencode** [comment]
Ok but system wide is overwritten if you previously installed the extension in .local/share (like from the extension website).
So you confirm there is no `~/.local/share/gnome-shell-extension/sound-output-device-chooser@kgshank.net` ?

**Comment by mattia-b89** [comment]
`~/.local/share/gnome-shell/extensions/` empty

**Comment by terencode** [comment]
Ok then I have no idea why it's not working for you :(
