### ISSUE TITLE
Port settings doesn't work on Ubuntu 20.04

### ISSUE THREAD

**Issue by raulcraveiro** [kgshank/gse-sound-output-device-chooser#97]
**Describe the bug**
When I was on Fedora 31, the "Port settings" was working normally. But now on Ubuntu 20.04, It doesn't show the devices. 

![image](https://user-images.githubusercontent.com/5623492/80313244-14c2c200-87c0-11ea-91af-18bd17a14e5d.png)

**Extension Information**
* Shell Version - Gnome 3.36
* Extension Version - How can I check this?
* Install method (extension.gnome.org, AUR etc.) - Extensions.gnome.org
* OS - Ubuntu 20.04

**Comment by ralleal** [comment]
I have the same problem. Same Ubuntu, same Gnome.

**Comment by kgshank** [comment]
It seems like python is not installed in Ubuntu by default. Try installing python and enable the option "Enable new profile identification". The old method doesn't work well if your OS display language is not English

**Comment by kgshank** [comment]
New version available for installation. Please check
